/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import control.OsControl;
import dao.OsDAO;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Item;
import model.Os;
import model.Pessoa;
import model.Usuario;
import model.Util;

/**
 *
 * @author Will
 */
public class Buscaos extends javax.swing.JDialog {

    OsControl oscontrol;
    Os o;
    List<Item> itens;

    /**
     * Creates new form Buscaos
     */
    public Buscaos(java.awt.Frame parent, boolean modal, String pesquisa) {
        super(parent, modal);
        initComponents();
        tbios.removeColumn(tbios.getColumnModel().getColumn(5));
        oscontrol = new OsControl();
        formos();
        formios();
        dataspesq();
        tfdescricao.setText(pesquisa);
        tbos.setAutoCreateRowSorter(true);
        //tbios.setAutoCreateRowSorter(true);
        o = new Os();
        populaospesq();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btok = new javax.swing.JButton();
        tfdescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbios = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btpesquisaos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbclifor = new javax.swing.JLabel();
        tfcliente = new javax.swing.JTextField();
        btpesqp = new javax.swing.JButton();
        tfcod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfdtai = new com.toedter.calendar.JDateChooser();
        tfdtfi = new com.toedter.calendar.JDateChooser();
        tfdtff = new com.toedter.calendar.JDateChooser();
        tfdtaf = new com.toedter.calendar.JDateChooser();
        tflimpar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        tfcodos = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca O.S");
        setModal(true);
        setResizable(false);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Para reordenar a coluna clique duas vezes sobre o Título");

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        tfdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdescricaoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdescricaoKeyTyped(evt);
            }
        });

        jLabel1.setText("Descrição Prod.");

        jLabel2.setText("Itens O.S (Selecionada)");

        jLabel4.setText("O.S (Selecionar)");

        tbos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod ", "Descrição O.S", "Data Abertura", "Data Fechamento", "Status", "Cod Cliente", "Cliente", "Usuário", "Obs", "Total R$", "Desconto %", "SubTotal R$", "Garantia Até"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbos.getTableHeader().setReorderingAllowed(false);
        tbos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbosMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbos);

        tbios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "UN", "Quantidade", "Valor Unitário", "Valor Total", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbios.getTableHeader().setReorderingAllowed(false);
        tbios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbiosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbios);

        jLabel7.setText("Data Abertura");

        jLabel8.setText("Data Fechamento");

        btpesquisaos.setText("Pesquisar O.S");
        btpesquisaos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesquisaosActionPerformed(evt);
            }
        });

        jLabel9.setText("Inicio");

        jLabel10.setText("Inicio");

        jLabel11.setText("Fim");

        jLabel12.setText("Fim");

        lbclifor.setText("Cliente");

        tfcliente.setEditable(false);

        btpesqp.setText("Pesquisar");
        btpesqp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqpActionPerformed(evt);
            }
        });

        tfcod.setEditable(false);

        jLabel13.setText("Cod Cliente");

        tflimpar.setText("Limpar Filtro");
        tflimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflimparActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Tipo Pesquisa");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer posição\t", "Inicio" }));
        jComboBox2.setEnabled(false);

        jLabel6.setText("Status");

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Andamento", "Fechado" }));
        cbstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbstatusItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jLabel14.setText("Cod O.S");

        tfcodos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfcodos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcodosFocusLost(evt);
            }
        });
        tfcodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcodosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdtai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdtfi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfdtaf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfdtff, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(297, 297, 297))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbclifor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfcliente))
                                            .addComponent(tfdescricao)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfcodos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(btpesqp)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(btpesquisaos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tflimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12))
                            .addComponent(tfdtai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdtaf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10))
                            .addComponent(tfdtfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdtff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btpesquisaos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tflimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tfcodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbclifor)
                            .addComponent(tfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btpesqp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btok)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        int posicao = tbos.getSelectedRow();
        if (posicao >= 0) {

            o.setCod(Integer.parseInt(tbos.getValueAt(posicao, 0).toString()));
            o.setDescricao(tbos.getValueAt(posicao, 1).toString());
            o.setDta(tbos.getValueAt(posicao, 2).toString());
            o.setDtf(tbos.getValueAt(posicao, 3).toString());
            o.setStatus(tbos.getValueAt(posicao, 4).toString());
            o.setCodclifor(Integer.parseInt(tbos.getValueAt(posicao, 5).toString()));
            o.setClifor(tbos.getValueAt(posicao, 6).toString());
            o.setUseros(tbos.getValueAt(posicao, 7).toString());
            o.setObs(tbos.getValueAt(posicao, 8).toString());
            o.setTotal(Double.parseDouble(tbos.getValueAt(posicao, 9).toString()));
            o.setDesconto(Double.parseDouble(tbos.getValueAt(posicao, 10).toString()));
            o.setSubtotal(Double.parseDouble(tbos.getValueAt(posicao, 11).toString()));
            o.setDtg(tbos.getValueAt(posicao, 12).toString());

            itens = new ArrayList<>();
            int l = tbios.getRowCount();
            for (int i = 0; i < l; i++) {
                Item it = new Item();
                it.setDescricao(tbios.getValueAt(i, 0).toString());
                it.setUN(tbios.getValueAt(i, 1).toString());
                it.setQtd(Double.parseDouble(tbios.getValueAt(i, 2).toString()));
                it.setVenda(Double.parseDouble(tbios.getValueAt(i, 3).toString()));
                it.setTotalitem(Double.parseDouble(tbios.getValueAt(i, 4).toString()));
                DefaultTableModel t = (DefaultTableModel) tbios.getModel();
                it.setId(Integer.parseInt(t.getValueAt(i, 5).toString()));
                itens.add(it);

            }

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro");
        }

    }//GEN-LAST:event_btokActionPerformed

    private void tfdescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdescricaoKeyTyped


    }//GEN-LAST:event_tfdescricaoKeyTyped

    private void tbosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbosMouseClicked


    }//GEN-LAST:event_tbosMouseClicked

    private void tbiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbiosMouseClicked

    }//GEN-LAST:event_tbiosMouseClicked

    private void cbstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbstatusItemStateChanged

    }//GEN-LAST:event_cbstatusItemStateChanged

    private void btpesquisaosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesquisaosActionPerformed

        DefaultTableModel t = (DefaultTableModel) tbios.getModel();
        t.setNumRows(0);

        populaospesq();

    }//GEN-LAST:event_btpesquisaosActionPerformed

    private void tbosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbosMousePressed

        if (evt.getClickCount() == 1) {
            int l = tbos.getSelectedRow();
            int codos = Integer.parseInt(tbos.getValueAt(l, 0).toString());
            populaios(codos);

    }//GEN-LAST:event_tbosMousePressed
        if (evt.getClickCount() == 2) {
            btok.doClick();
        }

    }
    private void btpesqpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqpActionPerformed
        Buscapessoa buscap;
        buscap = new Buscapessoa(null, true, "abrir", 0);
        buscap.setVisible(true);

        tfcod.setText(String.valueOf(buscap.p.getCodpessoa()));
        tfcliente.setText(buscap.p.getNome());


    }//GEN-LAST:event_btpesqpActionPerformed

    private void tflimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflimparActionPerformed
        tfcod.setText("");
        tfcodos.setText("");
        tfcliente.setText("");
        dataspesq();
        cbstatus.setSelectedIndex(0);
        tfdescricao.setText("");
        btpesquisaos.doClick();

    }//GEN-LAST:event_tflimparActionPerformed

    private void tfdescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdescricaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btpesquisaos.doClick();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfdescricaoKeyPressed

    private void tfcodosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcodosFocusLost

    }//GEN-LAST:event_tfcodosFocusLost

    private void tfcodosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcodosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btpesquisaos.doClick();

        }
    }//GEN-LAST:event_tfcodosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscaos dialog = new Buscaos(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btok;
    private javax.swing.JButton btpesqp;
    private javax.swing.JButton btpesquisaos;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbclifor;
    private javax.swing.JTable tbios;
    private javax.swing.JTable tbos;
    private javax.swing.JTextField tfcliente;
    private javax.swing.JTextField tfcod;
    private javax.swing.JFormattedTextField tfcodos;
    private javax.swing.JTextField tfdescricao;
    private com.toedter.calendar.JDateChooser tfdtaf;
    private com.toedter.calendar.JDateChooser tfdtai;
    private com.toedter.calendar.JDateChooser tfdtff;
    private com.toedter.calendar.JDateChooser tfdtfi;
    private javax.swing.JButton tflimpar;
    // End of variables declaration//GEN-END:variables

    private void formos() {
        tbos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbos.getColumnModel().getColumn(1).setPreferredWidth(220);
        tbos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbos.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbos.getColumnModel().getColumn(4).setPreferredWidth(80);
        tbos.getColumnModel().getColumn(5).setPreferredWidth(80);
        tbos.getColumnModel().getColumn(6).setPreferredWidth(180);
        tbos.getColumnModel().getColumn(7).setPreferredWidth(80);
        tbos.getColumnModel().getColumn(8).setPreferredWidth(200);
        tbos.getColumnModel().getColumn(9).setPreferredWidth(90);
        tbos.getColumnModel().getColumn(10).setPreferredWidth(90);
        tbos.getColumnModel().getColumn(11).setPreferredWidth(90);
        tbos.getColumnModel().getColumn(12).setPreferredWidth(90);

    }

    public void formios() {
        tbios.getColumnModel().getColumn(0).setPreferredWidth(250);
        tbios.getColumnModel().getColumn(1).setPreferredWidth(80);
        tbios.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbios.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbios.getColumnModel().getColumn(4).setPreferredWidth(100);

    }

    public void dataspesq() {

        tfdtai.setDate(Util.dataBR("01/01/1950"));
        tfdtfi.setDate(null);
        tfdtaf.setDate(Util.dataBR("30/12/2050"));
        tfdtff.setDate(null);

    }
//     int tamanho;
//            List<Usuario> lista = usuarioControl.listar();
//
//            tamanho = lista.size();
//            for (int i = 0; i < tamanho; i++) {
//                Usuario u = lista.get(i);

    public void populaos() {
        DefaultTableModel t = (DefaultTableModel) tbos.getModel();
        t.setNumRows(0);

        int tamanho;
        List<Os> lista = oscontrol.listar();

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Os os = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(os.getCod(), i, 0);
            t.setValueAt(os.getDescricao(), i, 1);
            t.setValueAt(Util.convertedataBR(os.getDta()), i, 2);
            if (os.getDtf() == null) {
                os.setDtf("");
                t.setValueAt(Util.convertedataBR(os.getDtf()), i, 3);
            }

            t.setValueAt(os.getStatus(), i, 4);
            t.setValueAt(os.getCodclifor(), i, 5);
            t.setValueAt(os.getClifor(), i, 6);
            t.setValueAt(os.getUseros(), i, 7);
            t.setValueAt(os.getObs(), i, 8);
            t.setValueAt(os.getTotal(), i, 9);
            t.setValueAt(os.getDesconto(), i, 10);
            t.setValueAt(os.getSubtotal(), i, 11);

        }
    }

    public void populaios(int cod) {

        DefaultTableModel t = (DefaultTableModel) tbios.getModel();
        t.setNumRows(0);
        formios();

        int tamanho;
        List<Item> lista = oscontrol.listarios(cod);

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Item prod = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(prod.getDescricao(), i, 0);
            t.setValueAt(prod.getUN(), i, 1);
            t.setValueAt(prod.getQtd(), i, 2);
            t.setValueAt(prod.getVenda(), i, 3);
            t.setValueAt(prod.getTotalitem(), i, 4);
            t.setValueAt(prod.getCodproduto(), i, 5);
        }

    }

    public void populaospesq() {

        DefaultTableModel t = (DefaultTableModel) tbos.getModel();
        t.setNumRows(0);
        String status = cbstatus.getSelectedItem().toString();

        if (cbstatus.getSelectedItem().equals("Todos")) {
            status = "";
        }
        if (tfcod.getText().equals("") || tfcodos.getText().equals("")) {
            if (tfcod.getText().equals("")) {
                tfcod.setText("0");
            }
            if (tfcodos.getText().equals("")) {
                tfcodos.setText("0");
            }

        }

        int tamanho;
        List<Os> lista = oscontrol.listaospesq(tfdescricao.getText(),
                Integer.parseInt(tfcod.getText()), status,
                Util.datatoStringUS(tfdtai.getDate()),
                Util.datatoStringUS(tfdtaf.getDate()),
                Util.datatoStringUS(tfdtfi.getDate()),
                Util.datatoStringUS(tfdtff.getDate()),
                Integer.parseInt(tfcodos.getText()));

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhuma O.S encontrado com o filtro selecionado");
        }

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Os os = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(os.getCod(), i, 0);
            t.setValueAt(os.getDescricao(), i, 1);
            t.setValueAt(Util.convertedataBR(os.getDta()), i, 2);
            if (os.getDtf() == null) {
                t.setValueAt("", i, 3);
            } else {
                t.setValueAt(Util.convertedataBR(os.getDtf()), i, 3);
            }
            t.setValueAt(os.getStatus(), i, 4);
            t.setValueAt(os.getCodclifor(), i, 5);
            t.setValueAt(os.getClifor(), i, 6);
            t.setValueAt(os.getUseros(), i, 7);
            t.setValueAt(os.getObs(), i, 8);
            t.setValueAt(os.getTotal(), i, 9);
            t.setValueAt(os.getDesconto(), i, 10);
            t.setValueAt(os.getSubtotal(), i, 11);
            if (os.getDtg() == null) {
                t.setValueAt("", i, 12);
            } else {
                t.setValueAt(Util.convertedataBR(os.getDtg()), i, 12);
            }

        }
    }

}
