/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ItemControl;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.*;
import control.*;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Will-Not
 */
public class Buscaitem extends javax.swing.JDialog {

    //   Item prod = new Item();
    private ItemControl produtoControl;
    Item p = new Item();

    public Buscaitem(java.awt.Frame parent, boolean modal, String texto) {
        super(parent, modal);
        initComponents();
        tfpesq.setText(texto);
        produtoControl = new ItemControl();
        tblprod.setAutoCreateRowSorter(true);

        populaprod();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblprod = new javax.swing.JTable();
        btok = new javax.swing.JButton();
        tfpesq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Itens");
        setResizable(false);

        tblprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Cod Interno", "Descrição", "Fornecedor", "UN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblprod.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblprod.getTableHeader().setReorderingAllowed(false);
        tblprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblprod);
        tblprod.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        tfpesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpesqKeyTyped(evt);
            }
        });

        jLabel1.setText("Pesquisar por");

        jLabel3.setText("Tipo Pesquisa");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer posição\t", "Inicio" }));
        jComboBox2.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Para reordenar a coluna clique duas vezes sobre o Título");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btok)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprodMouseClicked
        if (evt.getClickCount() == 2) {
            btok.doClick();

    }//GEN-LAST:event_tblprodMouseClicked
    }
    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed

        int posicao = tblprod.getSelectedRow();
        if (posicao >= 0) {

            p.setCodproduto(Integer.parseInt(tblprod.getValueAt(posicao, 0).toString()));
            p.setDescricao(tblprod.getValueAt(posicao, 1).toString());
            p.setDatacad(tblprod.getValueAt(posicao, 2).toString());
            p.setCusto(Double.parseDouble(tblprod.getValueAt(posicao, 3).toString()));
            p.setVenda(Double.parseDouble(tblprod.getValueAt(posicao, 4).toString()));
            p.setLucro(Double.parseDouble(tblprod.getValueAt(posicao, 5).toString()));
            p.setUN(tblprod.getValueAt(posicao, 6).toString());

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro");
        }
    }//GEN-LAST:event_btokActionPerformed

    private void tfpesqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqKeyTyped
        populaprod();
    }//GEN-LAST:event_tfpesqKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscaitem dialog = new Buscaitem(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btok;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblprod;
    private javax.swing.JTextField tfpesq;
    // End of variables declaration//GEN-END:variables
private void formprod() {

        tblprod.getColumnModel().getColumn(0).setHeaderValue("Cod");
        tblprod.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblprod.getColumnModel().getColumn(1).setHeaderValue("Item");
        tblprod.getColumnModel().getColumn(1).setPreferredWidth(160);
        tblprod.getColumnModel().getColumn(2).setHeaderValue("Data do Cadastro");
        tblprod.getColumnModel().getColumn(2).setPreferredWidth(110);
        tblprod.getColumnModel().getColumn(3).setHeaderValue("Custo R$");
        tblprod.getColumnModel().getColumn(4).setHeaderValue("Venda R$");
        tblprod.getColumnModel().getColumn(5).setHeaderValue("Lucro R$");

    }

    public void populaprod() {

        DefaultTableModel t = (DefaultTableModel) tblprod.getModel();
        t.setNumRows(0);
        formprod();

        int tamanho;
        List<Item> lista = produtoControl.listar2(tfpesq.getText());

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Item prod = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(prod.getCodproduto(), i, 0);
            t.setValueAt(prod.getDescricao(), i, 1);
            t.setValueAt(Util.convertedataBR(prod.getDatacad()), i, 2);
            t.setValueAt(prod.getCusto(), i, 3);
            t.setValueAt(prod.getVenda(), i, 4);
            t.setValueAt(prod.getLucro(), i, 5);
            t.setValueAt(prod.getUN(), i, 6);

        }

    }

}
