/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Pessoa;
import model.Usuario;
import dao.*;
import control.*;
import java.awt.Component;
import java.util.List;
import javafx.scene.control.PasswordField;
import view.CadastroPessoa;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Util;

/**
 *
 * @author Will-Not
 */
public final class Buscapessoa extends javax.swing.JDialog {

    public Usuario ug;
    public String nome;
    public String pesquisa;
    public int aba1;
    Pessoa p = new Pessoa();
    private PessoaControl pessoaControl;
    Usuario u = new Usuario();
    private UsuarioControl usuarioControl;

    public Buscapessoa(java.awt.Frame parent, boolean modal, String texto, int aba) {

        super(parent, modal);
        initComponents();
        pessoaControl = new PessoaControl();
        usuarioControl = new UsuarioControl();
        pesquisa = texto;
        if (pesquisa.equals("abrir")) {
           
        } else {
            tfpesquisap.setText(texto);
        }

        tblPessoa.setAutoCreateRowSorter(true);

        aba1 = aba;

        if (aba1 == 0) {
            if (tfpesquisap.getText().equals("")) {
                populacf();
            } else {
                populapp();
            }
        }
        if (aba1 == 1) {
            btncliente.setText("Novo Usuário");
            if (tfpesquisap.getText().equals("")) {
                populaut();
            } else {
                populaup();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        btpesqpessoaok = new javax.swing.JButton();
        tfpesquisap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btncliente = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Pessoas");
        setFocusTraversalPolicyProvider(true);

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "CPF / CNPJ", "Celular", "IE", "Endereco", "Numero", "Bairro", "Título 9", "Título 10", "Título 11", "Título 12", "Título 13", "Título 14", "Título 15", "Título 16", "Título 17", "Título 18", "Título 19", "Título 20", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPessoa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPessoa.getTableHeader().setReorderingAllowed(false);
        tblPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPessoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPessoa);
        tblPessoa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblPessoa.getColumnModel().getColumnCount() > 0) {
            tblPessoa.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblPessoa.getColumnModel().getColumn(1).setResizable(false);
            tblPessoa.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblPessoa.getColumnModel().getColumn(2).setResizable(false);
            tblPessoa.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPessoa.getColumnModel().getColumn(3).setResizable(false);
            tblPessoa.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        btpesqpessoaok.setText("OK");
        btpesqpessoaok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqpessoaokActionPerformed(evt);
            }
        });

        tfpesquisap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpesquisapKeyTyped(evt);
            }
        });

        jLabel1.setText("Pesquisar por");

        jLabel3.setText("Tipo Pesquisa");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer posição\t", "Inicio" }));
        jComboBox2.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Para reordenar a coluna clique duas vezes sobre o Título");

        btncliente.setText("Novo Cliente");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btpesqpessoaok, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfpesquisap, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfpesquisap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btpesqpessoaok)
                    .addComponent(btncliente))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btpesqpessoaokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqpessoaokActionPerformed
        int posicao = tblPessoa.getSelectedRow();
        if (posicao >= 0) {
            if (aba1 == 1) {

                u.setCodusuario(Integer.parseInt(tblPessoa.getValueAt(posicao, 0).toString()));
                u.setNome(tblPessoa.getValueAt(posicao, 1).toString());
                u.setSenha(tblPessoa.getValueAt(posicao, 2).toString());
                u.setPessoas(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 3).toString()));
                u.setUsuarios(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 4).toString()));
                u.setProdutos(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 5).toString()));
                u.setApagar(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 6).toString()));
                u.setAreceber(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 7).toString()));
                u.setOs(Boolean.parseBoolean(tblPessoa.getValueAt(posicao, 8).toString()));
                this.dispose();

            } else {
                p.setCodpessoa(Integer.parseInt(tblPessoa.getValueAt(posicao, 0).toString()));
                p.setNome(tblPessoa.getValueAt(posicao, 1).toString());
                p.setApelido(tblPessoa.getValueAt(posicao, 2).toString());
                p.setCPF(tblPessoa.getValueAt(posicao, 3).toString());
                String pessoa = tblPessoa.getValueAt(posicao, 4).toString();
                if (pessoa.equals("Física")) {
                    p.setPfisica(true);
                } else {
                    p.setPfisica(false);
                }
                p.setCelular(tblPessoa.getValueAt(posicao, 5).toString());
                p.setTelefone(tblPessoa.getValueAt(posicao, 6).toString());
                p.setEndereco(tblPessoa.getValueAt(posicao, 7).toString());
                p.setEnumero(tblPessoa.getValueAt(posicao, 8).toString());
                p.setBairro(tblPessoa.getValueAt(posicao, 9).toString());
                p.setComplemento(tblPessoa.getValueAt(posicao, 10).toString());
                p.setCEP(tblPessoa.getValueAt(posicao, 11).toString());
                p.setCidade(tblPessoa.getValueAt(posicao, 12).toString());
                p.setUF(tblPessoa.getValueAt(posicao, 13).toString());
                p.setNascimento(tblPessoa.getValueAt(posicao, 14).toString());
                p.setDatacadastro(tblPessoa.getValueAt(posicao, 15).toString());
                p.setRG(tblPessoa.getValueAt(posicao, 16).toString());
                p.setEmissorRG(tblPessoa.getValueAt(posicao, 17).toString());
                p.setSexo(tblPessoa.getValueAt(posicao, 18).toString());
                p.setEmail(tblPessoa.getValueAt(posicao, 19).toString());
                p.setOBS(tblPessoa.getValueAt(posicao, 20).toString());

                this.dispose();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Registro");
        }


    }//GEN-LAST:event_btpesqpessoaokActionPerformed

    private void tblPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPessoaMouseClicked
        if (evt.getClickCount() == 2) {
            btpesqpessoaok.doClick();
        }
    }//GEN-LAST:event_tblPessoaMouseClicked

    private void tfpesquisapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesquisapKeyTyped

        if (aba1 == 1) {
            populaup();
            //   JOptionPane.showMessageDialog(rootPane, aba1);
        } else {
            populapp();
            // JOptionPane.showMessageDialog(rootPane, aba1);
        }


    }//GEN-LAST:event_tfpesquisapKeyTyped

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed

        if (pesquisa.equals("abrir")) {
            this.dispose();
            new CadastroPessoa().setVisible(true);
        } else {
            this.dispose();
        }


    }//GEN-LAST:event_btnclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscapessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscapessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscapessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscapessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Buscapessoa dialog = new Buscapessoa(new javax.swing.JFrame(), true, null, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btpesqpessoaok;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField tfpesquisap;
    // End of variables declaration//GEN-END:variables
  public void populapp() {
        {
            DefaultTableModel t = (DefaultTableModel) tblPessoa.getModel();
            t.setNumRows(0);

            tabelacf();

            String pe = tfpesquisap.getText();
            int tamanho;
            try {

                Integer.parseInt(pe);
                List<Pessoa> lista = pessoaControl.getPessoaByCPF(pe);

                tamanho = lista.size();
                for (int i = 0; i < tamanho; i++) {
                    Pessoa pessoa = lista.get(i);

                    t.addRow(new Object[]{0});

                    t.setValueAt(pessoa.getCodpessoa(), i, 0);
                    t.setValueAt(pessoa.getNome(), i, 1);
                    t.setValueAt(pessoa.getApelido(), i, 2);
                    t.setValueAt(Util.formataCPF(pessoa.getCPF()), i, 3);
                    if (pessoa.isPfisica()) {
                        t.setValueAt("Física", i, 4);
                    } else {
                        t.setValueAt("Jurídica", i, 4);
                    }
                    t.setValueAt(pessoa.getCelular(), i, 5);
                    t.setValueAt(pessoa.getTelefone(), i, 6);
                    t.setValueAt(pessoa.getEndereco(), i, 7);
                    t.setValueAt(pessoa.getEnumero(), i, 8);
                    t.setValueAt(pessoa.getBairro(), i, 9);
                    t.setValueAt(pessoa.getComplemento(), i, 10);
                    t.setValueAt(pessoa.getCEP(), i, 11);
                    t.setValueAt(pessoa.getCidade(), i, 12);
                    t.setValueAt(pessoa.getUF(), i, 13);
                    t.setValueAt(Util.convertedataBR(pessoa.getNascimento()), i, 14);
                    t.setValueAt(Util.convertedataBR(pessoa.getDatacadastro()), i, 15);
                    t.setValueAt(pessoa.getRG(), i, 16);
                    t.setValueAt(pessoa.getEmissorRG(), i, 17);
                    t.setValueAt(pessoa.getSexo(), i, 18);
                    t.setValueAt(pessoa.getEmail(), i, 19);
                    t.setValueAt(pessoa.getOBS(), i, 20);
                }

            } catch (Exception ex) {
                List<Pessoa> lista = pessoaControl.getPessoaByNome(pe);

                tamanho = lista.size();
                for (int i = 0; i < tamanho; i++) {
                    Pessoa pessoa = lista.get(i);

                    t.addRow(new Object[]{0});

                    t.setValueAt(pessoa.getCodpessoa(), i, 0);
                    t.setValueAt(pessoa.getNome(), i, 1);
                    t.setValueAt(pessoa.getApelido(), i, 2);
                    t.setValueAt(Util.formataCPF(pessoa.getCPF()), i, 3);
                    if (pessoa.isPfisica()) {
                        t.setValueAt("Física", i, 4);
                    } else {
                        t.setValueAt("Jurídica", i, 4);
                    }
                    t.setValueAt(pessoa.getCelular(), i, 5);
                    t.setValueAt(pessoa.getTelefone(), i, 6);
                    t.setValueAt(pessoa.getEndereco(), i, 7);
                    t.setValueAt(pessoa.getEnumero(), i, 8);
                    t.setValueAt(pessoa.getBairro(), i, 9);
                    t.setValueAt(pessoa.getComplemento(), i, 10);
                    t.setValueAt(pessoa.getCEP(), i, 11);
                    t.setValueAt(pessoa.getCidade(), i, 12);
                    t.setValueAt(pessoa.getUF(), i, 13);
                    t.setValueAt(Util.convertedataBR(pessoa.getNascimento()), i, 14);
                    t.setValueAt(Util.convertedataBR(pessoa.getDatacadastro()), i, 15);
                    t.setValueAt(pessoa.getRG(), i, 16);
                    t.setValueAt(pessoa.getEmissorRG(), i, 17);
                    t.setValueAt(pessoa.getSexo(), i, 18);
                    t.setValueAt(pessoa.getEmail(), i, 19);
                    t.setValueAt(pessoa.getOBS(), i, 20);
                }

            }
        }
    }

    public void populaup() {
        {
            DefaultTableModel t = (DefaultTableModel) tblPessoa.getModel();
            t.setNumRows(0);

            tabelau();

            String usu = tfpesquisap.getText();
            int tamanho;
            List<Usuario> lista = usuarioControl.listar2(usu);
            // JOptionPane.showMessageDialog(rootPane, usu);
            tamanho = lista.size();
            for (int i = 0; i < tamanho; i++) {
                Usuario u = lista.get(i);

                t.addRow(new Object[]{0});

                t.setValueAt(u.getCodusuario(), i, 0);
                t.setValueAt(u.getNome(), i, 1);
                t.setValueAt(u.getSenha(), i, 2);
                t.setValueAt(u.isPessoas(), i, 3);
                t.setValueAt(u.isUsuarios(), i, 4);
                t.setValueAt(u.isProdutos(), i, 5);
                t.setValueAt(u.isApagar(), i, 6);
                t.setValueAt(u.isAreceber(), i, 7);
                t.setValueAt(u.isOs(), i, 8);

            }
        }
    }

    public void populaut() {
        {
            DefaultTableModel t = (DefaultTableModel) tblPessoa.getModel();
            t.setNumRows(0);
            tabelau();

            int tamanho;
            List<Usuario> lista = usuarioControl.listar();

            tamanho = lista.size();
            for (int i = 0; i < tamanho; i++) {
                Usuario u = lista.get(i);

                t.addRow(new Object[]{0});

                t.setValueAt(u.getCodusuario(), i, 0);
                t.setValueAt(u.getNome(), i, 1);
                t.setValueAt(u.getSenha(), i, 2);
                t.setValueAt(u.isPessoas(), i, 3);
                t.setValueAt(u.isUsuarios(), i, 4);
                t.setValueAt(u.isProdutos(), i, 5);
                t.setValueAt(u.isApagar(), i, 6);
                t.setValueAt(u.isAreceber(), i, 7);
                t.setValueAt(u.isOs(), i, 8);

            }
        }
    }

    public void recebepesq(String pesquisa) {
        tfpesquisap.setText(pesquisa);

    }

    private void tabelau() {
        tblPessoa.getColumnModel().getColumn(1).setHeaderValue("Usuário");
        tblPessoa.getColumnModel().getColumn(2).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(3).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(4).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(5).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(6).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(7).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(8).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(9).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(10).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(11).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(12).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(13).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(14).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(15).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(16).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(17).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(18).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(19).setPreferredWidth(0);
        tblPessoa.getColumnModel().getColumn(20).setPreferredWidth(0);

    }

    private void tabelacf() {
        tblPessoa.getColumnModel().getColumn(0).setHeaderValue("Cod");
        tblPessoa.getColumnModel().getColumn(0).setPreferredWidth(45);
        tblPessoa.getColumnModel().getColumn(1).setHeaderValue("Nome/Razão");
        tblPessoa.getColumnModel().getColumn(2).setHeaderValue("Apelido/Fantasia");
        tblPessoa.getColumnModel().getColumn(2).setPreferredWidth(180);
        tblPessoa.getColumnModel().getColumn(3).setHeaderValue("CPF/CNPJ");
        tblPessoa.getColumnModel().getColumn(3).setPreferredWidth(140);
        tblPessoa.getColumnModel().getColumn(4).setHeaderValue("Pessoa");
        tblPessoa.getColumnModel().getColumn(5).setHeaderValue("Celular");
        tblPessoa.getColumnModel().getColumn(5).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(6).setHeaderValue("Telefone");
        tblPessoa.getColumnModel().getColumn(6).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(7).setHeaderValue("Endereco");
        tblPessoa.getColumnModel().getColumn(7).setPreferredWidth(200);
        tblPessoa.getColumnModel().getColumn(8).setHeaderValue("Número");
        tblPessoa.getColumnModel().getColumn(9).setHeaderValue("Bairro");
        tblPessoa.getColumnModel().getColumn(9).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(10).setHeaderValue("Complemento");
        tblPessoa.getColumnModel().getColumn(10).setPreferredWidth(150);
        tblPessoa.getColumnModel().getColumn(11).setHeaderValue("CEP");
        tblPessoa.getColumnModel().getColumn(12).setHeaderValue("Cidade");
        tblPessoa.getColumnModel().getColumn(12).setPreferredWidth(150);
        tblPessoa.getColumnModel().getColumn(13).setHeaderValue("UF");
        tblPessoa.getColumnModel().getColumn(14).setHeaderValue("Nascimento");
        tblPessoa.getColumnModel().getColumn(14).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(15).setHeaderValue("Data do Cadastro");
        tblPessoa.getColumnModel().getColumn(15).setPreferredWidth(120);
        tblPessoa.getColumnModel().getColumn(16).setHeaderValue("RG/IE");
        tblPessoa.getColumnModel().getColumn(16).setPreferredWidth(160);
        tblPessoa.getColumnModel().getColumn(17).setHeaderValue("Emissor");
        tblPessoa.getColumnModel().getColumn(18).setHeaderValue("Sexo");
        tblPessoa.getColumnModel().getColumn(19).setHeaderValue("E-mail");
        tblPessoa.getColumnModel().getColumn(19).setPreferredWidth(200);
        tblPessoa.getColumnModel().getColumn(20).setHeaderValue("OBS");
        tblPessoa.getColumnModel().getColumn(20).setPreferredWidth(200);
    }

    public void populacf() {
        {
            DefaultTableModel t = (DefaultTableModel) tblPessoa.getModel();
            t.setNumRows(0);
            tabelacf();

            int tamanho;
            tamanho = pessoaControl.listar().size();
            for (int i = 0; i < tamanho; i++) {
                Pessoa pessoa = pessoaControl.listar().get(i);

                t.addRow(new Object[]{0});

                t.setValueAt(pessoa.getCodpessoa(), i, 0);
                t.setValueAt(pessoa.getNome(), i, 1);
                t.setValueAt(pessoa.getApelido(), i, 2);
                t.setValueAt(Util.formataCPF(pessoa.getCPF()), i, 3);
                if (pessoa.isPfisica()) {
                    t.setValueAt("Física", i, 4);
                } else {
                    t.setValueAt("Jurídica", i, 4);
                }
                t.setValueAt(pessoa.getCelular(), i, 5);
                t.setValueAt(pessoa.getTelefone(), i, 6);
                t.setValueAt(pessoa.getEndereco(), i, 7);
                t.setValueAt(pessoa.getEnumero(), i, 8);
                t.setValueAt(pessoa.getBairro(), i, 9);
                t.setValueAt(pessoa.getComplemento(), i, 10);
                t.setValueAt(pessoa.getCEP(), i, 11);
                t.setValueAt(pessoa.getCidade(), i, 12);
                t.setValueAt(pessoa.getUF(), i, 13);
                t.setValueAt(Util.convertedataBR(pessoa.getNascimento()), i, 14);
                t.setValueAt(Util.convertedataBR(pessoa.getDatacadastro()), i, 15);
                t.setValueAt(pessoa.getRG(), i, 16);
                t.setValueAt(pessoa.getEmissorRG(), i, 17);
                t.setValueAt(pessoa.getSexo(), i, 18);
                t.setValueAt(pessoa.getEmail(), i, 19);
                t.setValueAt(pessoa.getOBS(), i, 20);

            }
        }
    }
}
