/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Util;
import model.Pessoa;
import model.Usuario;
import control.*;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.Cnp;

public class CadastroPessoa extends javax.swing.JFrame {

    Buscapessoa buscap;
    int aba;
    int flag = 0;
    Pessoa p = new Pessoa();
    Usuario u = new Usuario();
    PessoaControl pcontrol = new PessoaControl();
    UsuarioControl ucontrol = new UsuarioControl();
    String uant;
    boolean cpfcnpj;

    public CadastroPessoa() {

        initComponents();
        desativacf();
        desativau();
        formf();
        tfsexo.setEnabled(false);
        btsalvar.setEnabled(false);
        btexcluir.setEnabled(false);
        rbf.setSelected(true);

        if (!Util.usuario.isUsuarios()) {
            tabcad.setEnabledAt(1, false);
        }
        cpfcnpj = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tabfor = new javax.swing.JPanel();
        lbestadual1 = new javax.swing.JLabel();
        tfiestadual = new javax.swing.JTextField();
        gppessoa = new javax.swing.JPanel();
        rbf1 = new javax.swing.JRadioButton();
        rbj1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfcod1 = new javax.swing.JTextField();
        lbnome1 = new javax.swing.JLabel();
        tfnome1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfendereco1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfcomplemento1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfemail1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfOBS1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        tfUF1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfCEP1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfenumero1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfcelular1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tftelefone1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfbairro1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tfcidade1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfdatacad1 = new javax.swing.JTextField();
        lbCPF1 = new javax.swing.JLabel();
        tfCPF1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        tffantasia = new javax.swing.JTextField();
        tfpesquisa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btpesq = new javax.swing.JButton();
        tabcad = new javax.swing.JTabbedPane();
        tabcli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbnome = new javax.swing.JLabel();
        tfnomerazao = new javax.swing.JTextField();
        tfendereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        tfcod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfbairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbsexo = new javax.swing.JLabel();
        tfsexo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfenumero = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfCEP = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfUF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfrgie = new javax.swing.JTextField();
        lbrgie = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbf = new javax.swing.JRadioButton();
        rbj = new javax.swing.JRadioButton();
        lbemissor = new javax.swing.JLabel();
        tfemissorrg = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfcomplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfOBS = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        lbnascimento = new javax.swing.JLabel();
        lbapelido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfcidade = new javax.swing.JTextField();
        tfapefan = new javax.swing.JTextField();
        lbtelefone = new javax.swing.JLabel();
        tfcpfcnpj = new javax.swing.JFormattedTextField();
        tfcelular = new javax.swing.JFormattedTextField();
        lbcpfcnpj = new javax.swing.JLabel();
        tfdatacad = new javax.swing.JTextField();
        tfnascimento = new javax.swing.JFormattedTextField();
        tftelefone = new javax.swing.JFormattedTextField();
        tabuser = new javax.swing.JPanel();
        tabusuario = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbos = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        cbpagar = new javax.swing.JCheckBox();
        cbreceber = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        cbpessoa = new javax.swing.JCheckBox();
        cbusuario = new javax.swing.JCheckBox();
        cbproduto = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        tfusuario = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        tfsenha = new javax.swing.JPasswordField();
        tfconfirmasenha = new javax.swing.JPasswordField();
        jLabel35 = new javax.swing.JLabel();
        tfcodu = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnovo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();

        lbestadual1.setText("IE");

        gppessoa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa"));

        buttonGroup1.add(rbf1);
        rbf1.setText("Física");

        buttonGroup1.add(rbj1);
        rbj1.setText("Jurídica");
        rbj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbj1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gppessoaLayout = new javax.swing.GroupLayout(gppessoa);
        gppessoa.setLayout(gppessoaLayout);
        gppessoaLayout.setHorizontalGroup(
            gppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gppessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbf1)
                .addGap(18, 18, 18)
                .addComponent(rbj1)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        gppessoaLayout.setVerticalGroup(
            gppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbf1)
                .addComponent(rbj1))
        );

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Campos obrigatórios marcados com *");

        jLabel2.setText("Código");

        tfcod1.setEnabled(false);

        lbnome1.setText("Razão Social*");

        jLabel7.setText("Endereço");

        jLabel13.setText("Complemento");

        jLabel24.setText("E-mail");

        jLabel28.setText("Observações");

        tfOBS1.setColumns(20);
        tfOBS1.setRows(5);
        jScrollPane2.setViewportView(tfOBS1);

        jLabel25.setText("UF");

        jLabel21.setText("CEP");

        jLabel17.setText("Número");

        jLabel9.setText("Celular*");

        jLabel14.setText("Telefone");

        jLabel15.setText("Bairro");

        jLabel32.setText("Cidade");

        jLabel19.setText("Data de Cadastro");

        lbCPF1.setText("CPF / CNPJ*");

        jLabel34.setText("Fantasia");

        javax.swing.GroupLayout tabforLayout = new javax.swing.GroupLayout(tabfor);
        tabfor.setLayout(tabforLayout);
        tabforLayout.setHorizontalGroup(
            tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabforLayout.createSequentialGroup()
                        .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabforLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36))
                            .addGroup(tabforLayout.createSequentialGroup()
                                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(lbnome1)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfemail1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(tabforLayout.createSequentialGroup()
                                    .addComponent(tfcod1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbCPF1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfCPF1))
                                .addComponent(tfendereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfnome1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcomplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel17)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabforLayout.createSequentialGroup()
                                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfUF1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(tfenumero1)
                                    .addComponent(tfCEP1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabforLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfcidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tabforLayout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(tabforLayout.createSequentialGroup()
                                        .addComponent(lbestadual1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfiestadual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tabforLayout.createSequentialGroup()
                                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tffantasia, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(tfcelular1))
                                .addGap(2, 2, 2)
                                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfbairro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabforLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tabforLayout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tfdatacad1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(tabforLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tftelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(54, 54, 54))
                    .addGroup(tabforLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabforLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gppessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addContainerGap(606, Short.MAX_VALUE)))
        );
        tabforLayout.setVerticalGroup(
            tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabforLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabforLayout.createSequentialGroup()
                        .addComponent(lbCPF1)
                        .addGap(3, 3, 3))
                    .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfcod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(tfcelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdatacad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(tfCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tftelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel34)
                    .addComponent(tffantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfenumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfendereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfbairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(tfcidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcomplemento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tfemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(tfiestadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbestadual1))
                .addGap(18, 18, 18)
                .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(tabforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabforLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(gppessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel6)
                    .addGap(252, 252, 252)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        tfpesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfpesquisaFocusGained(evt);
            }
        });
        tfpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpesquisaKeyPressed(evt);
            }
        });

        jLabel5.setText("Pesquisar");

        btpesq.setText("Pesquisar");
        btpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqActionPerformed(evt);
            }
        });

        tabcad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabcadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabcadMousePressed(evt);
            }
        });

        jLabel1.setText("Código");

        lbnome.setText("Nome / Razão*");

        jLabel3.setText("Endereço");

        lbCPF.setText("CPF / CNPJ *");

        tfcod.setEnabled(false);

        jLabel8.setText("Celular*");

        jLabel10.setText("Bairro");

        lbsexo.setText("Sexo");

        tfsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsexoActionPerformed(evt);
            }
        });

        jLabel12.setText("Complemento");

        jLabel20.setText("CEP");

        jLabel22.setText("UF");

        jLabel23.setText("E-mail");

        lbrgie.setText("Registro Geral");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa"));

        buttonGroup1.add(rbf);
        rbf.setText("Física");
        rbf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbfItemStateChanged(evt);
            }
        });
        rbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbj);
        rbj.setText("Jurídica");
        rbj.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbjItemStateChanged(evt);
            }
        });
        rbj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbf)
                .addGap(18, 18, 18)
                .addComponent(rbj)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbf)
                    .addComponent(rbj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbemissor.setText("Emissor");

        jLabel16.setText("Número");

        jLabel18.setText("Data de Cadastro");

        jLabel26.setText("Observações");

        tfOBS.setColumns(20);
        tfOBS.setRows(5);
        jScrollPane1.setViewportView(tfOBS);

        jLabel27.setText("Cidade");

        lbnascimento.setText("Nascimento");

        lbapelido.setText("Apelido");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Campos obrigatórios marcados com *");

        lbtelefone.setText("Telefone");

        tfcpfcnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcpfcnpjFocusLost(evt);
            }
        });

        try {
            tfcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(0xx##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfcelular.setDoubleBuffered(true);

        lbcpfcnpj.setForeground(new java.awt.Color(255, 0, 0));
        lbcpfcnpj.setText(" ");

        tfdatacad.setEditable(false);

        try {
            tfnascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tftelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout tabcliLayout = new javax.swing.GroupLayout(tabcli);
        tabcli.setLayout(tabcliLayout);
        tabcliLayout.setHorizontalGroup(
            tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabcliLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabcliLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addGap(60, 60, 60)
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel27))
                                    .addComponent(tfenumero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel10))
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(tfapefan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbsexo))
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbnascimento)))
                                .addGap(38, 38, 38))
                            .addGroup(tabcliLayout.createSequentialGroup()
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(lbrgie)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                        .addComponent(tfrgie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbemissor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfemissorrg, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addGap(55, 55, 55)
                                        .addComponent(tfemail)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(lbtelefone))
                                .addGap(41, 41, 41)
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfUF, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(tftelefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfcidade, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(tfnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfbairro)
                            .addComponent(tfdatacad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(tabcliLayout.createSequentialGroup()
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(tabcliLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbCPF)))
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbcpfcnpj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfcpfcnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                            .addGroup(tabcliLayout.createSequentialGroup()
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbnome)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(tfnomerazao))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lbapelido)
                            .addComponent(jLabel16)))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabcliLayout.setVerticalGroup(
            tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabcliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcpfcnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbCPF)
                                .addComponent(jLabel8)
                                .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfcpfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbnascimento)
                            .addComponent(tfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnomerazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbapelido)
                    .addComponent(tfapefan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsexo)
                    .addComponent(tfsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnome))
                .addGap(4, 4, 4)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfenumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(tfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)))
                .addGap(6, 6, 6)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(tfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel27)
                        .addComponent(tfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)))
                .addGap(12, 12, 12)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(tfdatacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabcliLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23)))
                .addGap(6, 6, 6)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbrgie)
                    .addComponent(tfrgie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbemissor)
                    .addComponent(tfemissorrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtelefone)
                    .addComponent(tftelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(tabcliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabcad.addTab("Cliente/Fornecedor", tabcli);

        tabuser.setEnabled(false);

        tabusuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuário"));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordem de Serviço"));

        cbos.setText("O.S");
        cbos.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(cbos)
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(cbos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Títulos"));

        cbpagar.setText("Pagar");
        cbpagar.setEnabled(false);

        cbreceber.setText("Receber");
        cbreceber.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbpagar)
            .addComponent(cbreceber)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(cbpagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbreceber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastros"));

        cbpessoa.setText("Pessoas");
        cbpessoa.setEnabled(false);
        cbpessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbpessoaItemStateChanged(evt);
            }
        });

        cbusuario.setText("Usuários");
        cbusuario.setEnabled(false);
        cbusuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbusuarioItemStateChanged(evt);
            }
        });

        cbproduto.setText("Itens");
        cbproduto.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbpessoa)
                    .addComponent(cbusuario)
                    .addComponent(cbproduto))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(cbpessoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbproduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel29.setText("Usuario*");

        tfusuario.setEnabled(false);
        tfusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfusuarioFocusLost(evt);
            }
        });
        tfusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusuarioActionPerformed(evt);
            }
        });

        jLabel30.setText("Senha*");

        jLabel31.setText("Confirmar Senha*");

        tfsenha.setEnabled(false);

        tfconfirmasenha.setEnabled(false);

        jLabel35.setText("Código");

        tfcodu.setEnabled(false);
        tfcodu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcoduActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabusuarioLayout = new javax.swing.GroupLayout(tabusuario);
        tabusuario.setLayout(tabusuarioLayout);
        tabusuarioLayout.setHorizontalGroup(
            tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfcodu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(tfconfirmasenha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(tfsenha)
                    .addComponent(tfusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabusuarioLayout.setVerticalGroup(
            tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabusuarioLayout.createSequentialGroup()
                .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabusuarioLayout.createSequentialGroup()
                        .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(tfcodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(tfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(tfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tfconfirmasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("Campos obrigatórios marcados com *");

        javax.swing.GroupLayout tabuserLayout = new javax.swing.GroupLayout(tabuser);
        tabuser.setLayout(tabuserLayout);
        tabuserLayout.setHorizontalGroup(
            tabuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabuserLayout.createSequentialGroup()
                        .addComponent(tabusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addGroup(tabuserLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabuserLayout.setVerticalGroup(
            tabuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabuserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(25, 25, 25)
                .addComponent(tabusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        tabcad.addTab("Usuário", tabuser);

        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/user.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield-1.png"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btpesq)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btcancelar)
                        .addContainerGap())
                    .addComponent(tabcad, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addComponent(tfpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btpesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(tabcad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnovo)
                    .addComponent(btsalvar)
                    .addComponent(btexcluir)
                    .addComponent(btcancelar))
                .addGap(649, 649, 649))
        );

        setSize(new java.awt.Dimension(825, 538));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqActionPerformed
        desativacf();
        desativau();
        limpatelacf();
        limpatelau();
        btnovo.setEnabled(true);
        btsalvar.setEnabled(false);
        btexcluir.setEnabled(false);
        if (Util.usuario.getNome().equals("admin")) {
            btexcluir.setEnabled(true);
        }

        aba = tabcad.getSelectedIndex();
        buscap = new Buscapessoa(this, true, tfpesquisa.getText(), aba);
        buscap.setVisible(true);
        if (aba == 0 && buscap.p.getCodpessoa() != 0) {
            if (buscap.p.isPfisica()) {
                rbf.setSelected(true);

                formf();
            } else {
                rbj.setSelected(true);

                formj();
            }
            tfcod.setText(String.valueOf(buscap.p.getCodpessoa()));
            tfnomerazao.setText(buscap.p.getNome());
            tfcpfcnpj.setText(buscap.p.getCPF());
            tfcelular.setText(buscap.p.getCelular());
            tfnascimento.setText(buscap.p.getNascimento());
            tfapefan.setText(buscap.p.getApelido());
            tfsexo.setText(buscap.p.getSexo());
            tfendereco.setText(buscap.p.getEndereco());
            tfenumero.setText(buscap.p.getEnumero());
            tfbairro.setText(buscap.p.getBairro());
            tfcomplemento.setText(buscap.p.getComplemento());
            tfCEP.setText(buscap.p.getCEP());
            tfcidade.setText(buscap.p.getCidade());
            tfemail.setText(buscap.p.getEmail());
            tfUF.setText(buscap.p.getUF());
            tfdatacad.setText(buscap.p.datacadastro);
            tfrgie.setText(buscap.p.getRG());
            tfemissorrg.setText(buscap.p.getEmissorRG());
            tftelefone.setText(buscap.p.getTelefone());
            tfOBS.setText(buscap.p.getOBS());
            cpfcnpj = true;

        } else {

            tfcodu.setText(String.valueOf(buscap.u.getCodusuario()));
            tfusuario.setText(buscap.u.getNome());
            tfsenha.setText(buscap.u.getSenha());
            tfconfirmasenha.setText(buscap.u.getSenha());
            cbpessoa.setSelected(buscap.u.isPessoas());
            cbusuario.setSelected(buscap.u.isUsuarios());
            cbproduto.setSelected(buscap.u.isProdutos());
            cbpagar.setSelected(buscap.u.isApagar());
            cbreceber.setSelected(buscap.u.isAreceber());
            cbos.setSelected(buscap.u.isOs());
            uant = buscap.u.getNome();

        }

        if (buscap.p.getCodpessoa() != 0 || buscap.u.getCodusuario() != 0) {
            if (aba == 0) {
                ativacf();
                btsalvar.setEnabled(true);
                btnovo.setEnabled(false);
                tabcad.setEnabledAt(1, false);
                flag = 2;
                if (!buscap.p.isPfisica()) {
                    tfsexo.setEnabled(false);
                }

            } else {
                ativau();
                btsalvar.setEnabled(true);
                btnovo.setEnabled(false);
                btexcluir.setEnabled(true);
                tabcad.setEnabledAt(0, false);
                flag = 2;
            }

        }
    }//GEN-LAST:event_btpesqActionPerformed

    public void formj() {

        tfcpfcnpj.setValue(null);
        JFormattedTextField cnpj = new JFormattedTextField();
        try {
            tfcpfcnpj.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("##.###.###/####-##")));
        } catch (ParseException e) {
        }

        lbapelido.setText("Fantasia");
        lbrgie.setText("Inscrição Est.");
        tfsexo.setEnabled(false);

    }

    public void formf() {

        tfcpfcnpj.setValue(null);

        JFormattedTextField cpf = new JFormattedTextField();

        try {
            tfcpfcnpj.setFormatterFactory(new DefaultFormatterFactory(
                    new MaskFormatter("###.###.###-##")));
        } catch (ParseException e) {
        }

        lbapelido.setText("Apelido");
        lbrgie.setText("Registro Geral");
        tfsexo.setEnabled(true);

    }

    public void desativau() {
        tfusuario.setEnabled(false);
        tfsenha.setEnabled(false);
        tfconfirmasenha.setEnabled(false);
        cbpessoa.setEnabled(false);
        cbproduto.setEnabled(false);
        cbusuario.setEnabled(false);
        cbpagar.setEnabled(false);
        cbreceber.setEnabled(false);
        cbos.setEnabled(false);

    }

    public void ativau() {
        tfusuario.setEnabled(true);
        tfsenha.setEnabled(true);
        tfconfirmasenha.setEnabled(true);
        cbpessoa.setEnabled(true);
        cbproduto.setEnabled(true);
        cbusuario.setEnabled(true);
        cbpagar.setEnabled(true);
        cbreceber.setEnabled(true);
        cbos.setEnabled(true);
    }

    public void limpatelacf() {
        tfcod.setText("");
        tfcpfcnpj.setText("");
        tfcelular.setText("");
        tfnomerazao.setText("");
        tfapefan.setText("");
        tfendereco.setText("");
        tfenumero.setText("");
        tfbairro.setText("");
        tfcomplemento.setText("");
        tfCEP.setText("");
        tfcidade.setText("");
        tfemail.setText("");
        tfUF.setText("");
        tfdatacad.setText("");
        tfrgie.setText("");
        tfemissorrg.setText("");
        tfsexo.setText("");
        tfnascimento.setText("");
        tfOBS.setText("");
        rbf.setSelected(true);
        tftelefone.setText("");
    }

    public void limpatelau() {
        tfcodu.setText("");
        tfusuario.setText("");
        tfsenha.setText("");
        tfconfirmasenha.setText("");
        cbpessoa.setSelected(false);
        cbproduto.setSelected(false);
        cbusuario.setSelected(false);
        cbpagar.setSelected(false);
        cbreceber.setSelected(false);
        cbos.setSelected(false);

    }

    public void desativacf() {
        tfcpfcnpj.setEnabled(false);
        tfcelular.setEnabled(false);
        tfnomerazao.setEnabled(false);
        tfapefan.setEnabled(false);
        tfendereco.setEnabled(false);
        tfenumero.setEnabled(false);
        tfbairro.setEnabled(false);
        tfcomplemento.setEnabled(false);
        tfCEP.setEnabled(false);
        tfcidade.setEnabled(false);
        tfemail.setEnabled(false);
        tfUF.setEnabled(false);
        tfdatacad.setEnabled(false);
        tfrgie.setEnabled(false);
        tfemissorrg.setEnabled(false);
        tfsexo.setEnabled(false);
        tfnascimento.setEnabled(false);
        tfOBS.setEnabled(false);
        rbf.setEnabled(false);
        rbj.setEnabled(false);
        tftelefone.setEnabled(false);

    }

    public void ativacf() {
        tfcpfcnpj.setEnabled(true);
        tfcelular.setEnabled(true);
        tfnomerazao.setEnabled(true);
        tfapefan.setEnabled(true);
        tfendereco.setEnabled(true);
        tfenumero.setEnabled(true);
        tfbairro.setEnabled(true);
        tfcomplemento.setEnabled(true);
        tfCEP.setEnabled(true);
        tfcidade.setEnabled(true);
        tfemail.setEnabled(true);
        tfUF.setEnabled(true);
        tfdatacad.setEnabled(true);
        tfrgie.setEnabled(true);
        tfemissorrg.setEnabled(true);
        tfsexo.setEnabled(true);
        tfnascimento.setEnabled(true);
        tfOBS.setEnabled(true);
        tabcad.setEnabledAt(1, true);
        rbf.setEnabled(true);
        rbj.setEnabled(true);
        tftelefone.setEnabled(true);
    }


    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        aba = tabcad.getSelectedIndex();
        if (aba == 0) {

            String nomecampos = "";
            if (tfnomerazao.getText().equals("") | tfcpfcnpj.getText().equals("   .   .   -  ")
                    | tfcpfcnpj.getText().equals("  .   .   /    -  ") | tfcelular.getText().equals("(0xx  )     -    ") | !cpfcnpj) {
                if (tfnomerazao.getText().equals("")) {

                    nomecampos += " Nome ";
                    tfnomerazao.requestFocus();
                }
                if (tfcpfcnpj.getText().equals("   .   .   -  ") | tfcpfcnpj.getText().equals("  .   .   /    -  ")) {

                    nomecampos += ", CPF/CNPJ ";
                }
                if (tfcelular.getText().equals("(0xx  )     -    ")) {

                    nomecampos += ", Celular ";

                }
                JOptionPane.showMessageDialog(cbos, "Preencha o(s) campo(s) obrigatórios (" + nomecampos + ")");
            } else {
                if (flag == 1) {

                    if (pcontrol.salvar(rbf.isSelected(), tfnomerazao.getText(), Util.limpaCPF(tfcpfcnpj.getText()), tfcelular.getText(), Util.convertedataUS(tfnascimento.getText()), tfendereco.getText(),
                            tfapefan.getText(), tfsexo.getText(), tfenumero.getText(), tfbairro.getText(), tfcomplemento.getText(), tfCEP.getText(),
                            tfcidade.getText(), tfemail.getText(), tfUF.getText(), Util.convertedataUS(tfdatacad.getText()), tfrgie.getText(), tfemissorrg.getText(),
                            tftelefone.getText(), tfOBS.getText())) {
                        JOptionPane.showMessageDialog(cbos, "Cadastro efetuado com sucesso");
                        limpatelacf();
                        btnovo.setEnabled(true);
                        btsalvar.setEnabled(false);
                        btexcluir.setEnabled(false);
                        tabcad.setEnabledAt(1, true);
                        desativacf();

                    } else {
                        JOptionPane.showMessageDialog(cbos, "Cadastro não efetuado");
                    }

                }
                if (flag == 2) {
                    if (pcontrol.alterar(Integer.parseInt(tfcod.getText()), rbf.isSelected(), tfnomerazao.getText(), Util.limpaCPF(tfcpfcnpj.getText()), tfcelular.getText(), Util.convertedataUS(tfnascimento.getText()), tfendereco.getText(),
                            tfapefan.getText(), tfsexo.getText(), tfenumero.getText(), tfbairro.getText(), tfcomplemento.getText(), tfCEP.getText(),
                            tfcidade.getText(), tfemail.getText(), tfUF.getText(), Util.convertedataUS(tfdatacad.getText()), tfrgie.getText(), tfemissorrg.getText(),
                            tftelefone.getText(), tfOBS.getText())) {
                        JOptionPane.showMessageDialog(cbos, "Cadastro '" + tfnomerazao.getText() + "' alterado com sucesso");
                        limpatelacf();
                        btnovo.setEnabled(true);
                        btsalvar.setEnabled(false);
                        btexcluir.setEnabled(false);
                        tabcad.setEnabledAt(1, true);
                        desativacf();

                    } else {
                        JOptionPane.showMessageDialog(cbos, "Alteração não efetuado");
                    }

                }

            }
        }
        if (aba == 1) {

            if (tfusuario.getText().equals("") | tfsenha.getText().equals("")) {
                JOptionPane.showMessageDialog(cbos, "Preencha os campos obrigatórios");
            } else {
                if (flag == 1) {
                    if (String.valueOf(tfsenha.getPassword()).equals(String.valueOf(tfconfirmasenha.getPassword()))) {

                        if (ucontrol.salvar(tfusuario.getText(), tfsenha.getText(), cbpessoa.isSelected(),
                                cbusuario.isSelected(), cbproduto.isSelected(), cbpagar.isSelected(), cbreceber.isSelected(), cbos.isSelected())) {
                            JOptionPane.showMessageDialog(cbos, "Cadastro efetuado com sucesso");
                            limpatelau();
                            btnovo.setEnabled(true);
                            btsalvar.setEnabled(false);
                            btexcluir.setEnabled(false);
                            tabcad.setEnabledAt(0, true);
                            desativau();

                        } else {
                            JOptionPane.showMessageDialog(cbos, "Cadastro não efetuado");
                        }
                    } else {
                        JOptionPane.showMessageDialog(cbos, "A senha e a confirmação da senha não correspondem. Favor preencher corretamente");
                    }
                }
                if (flag == 2) {

                    if (String.valueOf(tfsenha.getPassword()).equals(String.valueOf(tfconfirmasenha.getPassword()))) {
                        u.setNome(tfusuario.getText());
                        u.setSenha(tfsenha.getText());

                        if (ucontrol.alterar(Integer.parseInt(tfcodu.getText()), tfusuario.getText(), tfsenha.getText(), cbpessoa.isSelected(),
                                cbusuario.isSelected(), cbproduto.isSelected(), cbpagar.isSelected(), cbreceber.isSelected(), cbos.isSelected())) {
                            JOptionPane.showMessageDialog(cbos, "Cadastro Alterado com sucesso");
                            limpatelau();
                            desativau();
                            btnovo.setEnabled(true);
                            btsalvar.setEnabled(false);
                            btexcluir.setEnabled(false);
                            tabcad.setEnabledAt(0, true);

                        } else {
                            JOptionPane.showMessageDialog(cbos, "Usuário já existente");
                        }
                    } else {
                        JOptionPane.showMessageDialog(cbos, "A senha e a confirmação da senha não correspondem. Favor preencher corretamente");
                    }

                }
            }
        }
    }//GEN-LAST:event_btsalvarActionPerformed


    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        aba = tabcad.getSelectedIndex();

        if (aba == 1) {
            String udel;
            udel = tfusuario.getText();
            int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o usuário " + udel + "?", "Tem certeza ?", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                if (ucontrol.excluir(Integer.parseInt(tfcodu.getText())));
                {

                    JOptionPane.showMessageDialog(cbos, "Usuário " + udel + " excluido com sucesso");
                    limpatelau();
                    desativau();
                    btsalvar.setEnabled(false);
                    btnovo.setEnabled(true);
                    btexcluir.setEnabled(false);
                    tabcad.setEnabledAt(0, true);
                }

            } else {
                JOptionPane.showMessageDialog(cbos, "Nehuma alteração realizada");
            }

        }
        if (aba == 0) {
            String pdel;
            pdel = tfnomerazao.getText();
            int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Cadastro " + pdel + "?", "Tem certeza ?", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                if (pcontrol.excluir(Integer.parseInt(tfcod.getText())));
                {

                    JOptionPane.showMessageDialog(cbos, "Cadastro " + pdel + " excluido com sucesso");
                    limpatelacf();
                    desativacf();
                    btsalvar.setEnabled(false);
                    btnovo.setEnabled(true);
                    btexcluir.setEnabled(false);
                    tabcad.setEnabledAt(1, true);
                }

            } else {
                JOptionPane.showMessageDialog(cbos, "Nehuma alteração realizada");
            }
        }


    }//GEN-LAST:event_btexcluirActionPerformed
    private void msgnovo() {
        JOptionPane.showMessageDialog(cbos, "Insira os dados depois clique em salvar");
    }

    private void acaobtnovo() {
        btsalvar.setEnabled(true);
        btnovo.setEnabled(false);
        btexcluir.setEnabled(false);

    }

    public void datacad() {
        Date data = new Date();
        SimpleDateFormat databr = new SimpleDateFormat("dd/MM/yyyy");

        tfdatacad.setText(databr.format(data));

    }


    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        aba = tabcad.getSelectedIndex();
        if (aba == 0) {
            msgnovo();
            flag = 1;
            ativacf();
            desativau();
            tabcad.setEnabledAt(1, false);
            datacad();
            acaobtnovo();
        }
        if (aba == 1) {
            msgnovo();
            flag = 1;
            desativacf();
            ativau();
            tabcad.setEnabledAt(0, false);
            acaobtnovo();
            //btexcluir.setEnabled(false);
        }


    }//GEN-LAST:event_btnovoActionPerformed


    private void tfpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btpesq.doClick();

        }
    }//GEN-LAST:event_tfpesquisaKeyPressed

    private void tfpesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfpesquisaFocusGained

    }//GEN-LAST:event_tfpesquisaFocusGained

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Cancelar (As Alterações realizadas serão perdidos se não clicar em salvar) ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            desativacf();
            desativau();
            limpatelacf();
            limpatelau();
            btexcluir.setEnabled(false);
            btsalvar.setEnabled(false);
            btnovo.setEnabled(true);
            flag = 0;
            tabcad.setEnabledAt(0, true);
            tabcad.setEnabledAt(1, true);
            lbcpfcnpj.setText("");
        } else {
            JOptionPane.showMessageDialog(cbos, "Clique em salvar para guardar os dados");
        }


    }//GEN-LAST:event_btcancelarActionPerformed

    private void tabcadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcadMousePressed


    }//GEN-LAST:event_tabcadMousePressed

    private void tabcadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabcadMouseClicked
        aba = tabcad.getSelectedIndex();
    }//GEN-LAST:event_tabcadMouseClicked

    private void tfcoduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcoduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcoduActionPerformed

    private void tfusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusuarioActionPerformed

    }//GEN-LAST:event_tfusuarioActionPerformed

    private void tfusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfusuarioFocusLost

        Usuario u = ucontrol.getUsuarioByUser2(tfusuario.getText());
        if (u != null && flag == 1) {

            JOptionPane.showMessageDialog(rootPane, "Usuário " + tfusuario.getText() + " já cadastrado favor utilizar outro "
                    + "nome de usuário");
            tfusuario.requestFocus();
        } else {

        }
    }//GEN-LAST:event_tfusuarioFocusLost

    private void cbusuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbusuarioItemStateChanged
        if (cbpessoa.isSelected()) {

        } else {
            cbpessoa.setSelected(true);
        }
    }//GEN-LAST:event_cbusuarioItemStateChanged

    private void cbpessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbpessoaItemStateChanged
        if (cbusuario.isSelected()) {
            cbpessoa.setSelected(true);
        }
    }//GEN-LAST:event_cbpessoaItemStateChanged

    private void rbj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbj1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbj1ActionPerformed

    private void rbjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbjActionPerformed
        formj();
        tfsexo.setText("");
    }//GEN-LAST:event_rbjActionPerformed

    private void rbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfActionPerformed

        formf();


    }//GEN-LAST:event_rbfActionPerformed

    private void tfsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsexoActionPerformed

    private void rbfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbfItemStateChanged

    }//GEN-LAST:event_rbfItemStateChanged

    private void rbjItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbjItemStateChanged

    }//GEN-LAST:event_rbjItemStateChanged

    private void tfcpfcnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcpfcnpjFocusLost
        if (tfcpfcnpj.getText().equals("   .   .   -  ") | tfcpfcnpj.getText().equals("  .   .   /    -  ")) {
            lbcpfcnpj.setText("Preencha o CPF/CNPJ");
            tfcpfcnpj.requestFocus();
    }//GEN-LAST:event_tfcpfcnpjFocusLost
        
    else {
            if (rbf.isSelected()) {
                if (Cnp.isValidCPF(tfcpfcnpj.getText().replace(".", "").replace("-", "").replace(" ", ""))) {
                    lbcpfcnpj.setText("");
                    cpfcnpj = true;
                } else {
                    lbcpfcnpj.setText("CPF Inválido");
                    tfcpfcnpj.requestFocus();
                    cpfcnpj = false;
                }

            }
            if (rbj.isSelected()) {
                if (Cnp.isValidCNPJ(tfcpfcnpj.getText().replace(".", "").replace("-", "").replace("/", "").replace(" ", ""))) {
                    lbcpfcnpj.setText("");
                    cpfcnpj = true;
                } else {
                    lbcpfcnpj.setText("CNPJ Inválido");
                    tfcpfcnpj.requestFocus();
                    cpfcnpj = false;
                }
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroPessoa().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btpesq;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbos;
    private javax.swing.JCheckBox cbpagar;
    private javax.swing.JCheckBox cbpessoa;
    private javax.swing.JCheckBox cbproduto;
    private javax.swing.JCheckBox cbreceber;
    private javax.swing.JCheckBox cbusuario;
    private javax.swing.JPanel gppessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCPF1;
    private javax.swing.JLabel lbapelido;
    private javax.swing.JLabel lbcpfcnpj;
    private javax.swing.JLabel lbemissor;
    private javax.swing.JLabel lbestadual1;
    private javax.swing.JLabel lbnascimento;
    private javax.swing.JLabel lbnome;
    private javax.swing.JLabel lbnome1;
    private javax.swing.JLabel lbrgie;
    private javax.swing.JLabel lbsexo;
    private javax.swing.JLabel lbtelefone;
    private javax.swing.JRadioButton rbf;
    private javax.swing.JRadioButton rbf1;
    private javax.swing.JRadioButton rbj;
    private javax.swing.JRadioButton rbj1;
    private javax.swing.JTabbedPane tabcad;
    private javax.swing.JPanel tabcli;
    private javax.swing.JPanel tabfor;
    private javax.swing.JPanel tabuser;
    private javax.swing.JPanel tabusuario;
    private javax.swing.JTextField tfCEP;
    private javax.swing.JTextField tfCEP1;
    private javax.swing.JTextField tfCPF1;
    private javax.swing.JTextArea tfOBS;
    private javax.swing.JTextArea tfOBS1;
    private javax.swing.JTextField tfUF;
    private javax.swing.JTextField tfUF1;
    private javax.swing.JTextField tfapefan;
    private javax.swing.JTextField tfbairro;
    private javax.swing.JTextField tfbairro1;
    private javax.swing.JFormattedTextField tfcelular;
    private javax.swing.JTextField tfcelular1;
    private javax.swing.JTextField tfcidade;
    private javax.swing.JTextField tfcidade1;
    private javax.swing.JTextField tfcod;
    private javax.swing.JTextField tfcod1;
    private javax.swing.JTextField tfcodu;
    private javax.swing.JTextField tfcomplemento;
    private javax.swing.JTextField tfcomplemento1;
    private javax.swing.JPasswordField tfconfirmasenha;
    private javax.swing.JFormattedTextField tfcpfcnpj;
    private javax.swing.JTextField tfdatacad;
    private javax.swing.JTextField tfdatacad1;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfemail1;
    private javax.swing.JTextField tfemissorrg;
    private javax.swing.JTextField tfendereco;
    private javax.swing.JTextField tfendereco1;
    private javax.swing.JTextField tfenumero;
    private javax.swing.JTextField tfenumero1;
    private javax.swing.JTextField tffantasia;
    private javax.swing.JTextField tfiestadual;
    private javax.swing.JFormattedTextField tfnascimento;
    private javax.swing.JTextField tfnome1;
    private javax.swing.JTextField tfnomerazao;
    private javax.swing.JTextField tfpesquisa;
    private javax.swing.JTextField tfrgie;
    private javax.swing.JPasswordField tfsenha;
    private javax.swing.JTextField tfsexo;
    private javax.swing.JFormattedTextField tftelefone;
    private javax.swing.JTextField tftelefone1;
    private javax.swing.JTextField tfusuario;
    // End of variables declaration//GEN-END:variables
}
