/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import control.*;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import model.Util;

/**
 *
 *
 */
public class CadastroItem extends javax.swing.JFrame {

    ItemControl prodcontrol;
    Buscaitem buscaprod;
    int flag = 0;
    Double custo;
    Double margem;
    Double venda;
    Double qtd;
    Double marg;
    Double sub;
    DecimalFormat dc;

    public CadastroItem() {
        initComponents();
        desativatela();
        formun(tfun);
        dc = new DecimalFormat("0.00");
        prodcontrol = new ItemControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoRadialProdutos = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnovo = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btpesq = new javax.swing.JButton();
        tfpesq = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tfcod = new javax.swing.JTextField();
        tfdescricao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jlbreal1 = new javax.swing.JLabel();
        jlbreal = new javax.swing.JLabel();
        tfvenda = new javax.swing.JFormattedTextField();
        tfmargem = new javax.swing.JFormattedTextField();
        tfcusto = new javax.swing.JFormattedTextField();
        tfdatacad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btcancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfun = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Item");
        setResizable(false);

        jLabel2.setText("Cod Interno");

        jLabel3.setText("Descrição*");

        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/user.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield-1.png"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        btpesq.setText("Pesquisar");
        btpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqActionPerformed(evt);
            }
        });

        jLabel9.setText("Pesquisar");

        tfcod.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        jLabel13.setText("Custo*");

        jLabel15.setText("Preço de Venda* ");

        jLabel20.setText("Lucro* %");

        jlbreal1.setText("R$");

        jlbreal.setText("R$");

        tfvenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));

        tfmargem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));
        tfmargem.setToolTipText("Digite o Lucro em porcentagem");
        tfmargem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfmargemFocusLost(evt);
            }
        });

        tfcusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbreal1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbreal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfmargem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20)
                    .addComponent(jlbreal1)
                    .addComponent(tfmargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jlbreal)
                    .addComponent(tfvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        tfdatacad.setEditable(false);
        tfdatacad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfdatacadFocusGained(evt);
            }
        });

        jLabel6.setText("Data do cadastro");

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        jLabel7.setText("UN*");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Campos obrigatórios marcados com *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdatacad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfun, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(btpesq)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btcancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btpesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdatacad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(tfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnovo)
                    .addComponent(btsalvar)
                    .addComponent(btexcluir)
                    .addComponent(btcancelar))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(707, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqActionPerformed
        limpatela();
        desativatela();

        buscaprod = new Buscaitem(this, true, tfpesq.getText());
        buscaprod.setVisible(true);
        if (buscaprod.p.getCodproduto() >= 1) {
            tfcod.setText(String.valueOf(buscaprod.p.getCodproduto()));
            tfdescricao.setText(buscaprod.p.getDescricao());
            tfdatacad.setText(buscaprod.p.getDatacad());
            tfcusto.setText(String.valueOf(dc.format(buscaprod.p.getCusto())));
            tfvenda.setText(String.valueOf(dc.format(buscaprod.p.getVenda())));
            tfmargem.setText(String.valueOf(dc.format(buscaprod.p.getLucro())));
            tfun.setText(String.valueOf(buscaprod.p.getUN()));
            btnovo.setEnabled(false);
            btsalvar.setEnabled(true);
            btexcluir.setEnabled(true);
            ativatela();
            flag = 2;

        } else {
            btnovo.setEnabled(true);
        }

    }//GEN-LAST:event_btpesqActionPerformed

    private void tfdatacadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdatacadFocusGained

    }//GEN-LAST:event_tfdatacadFocusGained

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        if (tfdescricao.getText().equals("") | tfcusto.getText().equals("") | tfmargem.getText().equals("")
                | tfvenda.getText().equals("") | tfun.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos obrigatórios");

        } else {

            if (flag == 1) {
                if (prodcontrol.salvar(tfdescricao.getText(), Util.convertedataUS(tfdatacad.getText()), Double.parseDouble(tfcusto.getText().replace(",", ".")),
                        Double.parseDouble(tfvenda.getText().replace(",", ".")), Double.parseDouble(tfmargem.getText().replace(",", ".")), tfun.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Item cadastrado com sucesso");

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Item não cadastrado");
                }

            }
            if (flag == 2) {
                if (prodcontrol.alterar(Integer.parseInt(tfcod.getText()), tfdescricao.getText(), Util.convertedataUS(tfdatacad.getText()), Double.parseDouble(tfcusto.getText().replace(",", ".")),
                        Double.parseDouble(tfvenda.getText().replace(",", ".")), Double.parseDouble(tfmargem.getText().replace(",", ".")), tfun.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Item Alterado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Item não alterado");
                }
            }
            limpatela();
            desativatela();
            btnovo.setEnabled(true);
        }


    }//GEN-LAST:event_btsalvarActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Cancelar (As Alterações realizadas serão perdidas se não clicar em salvar) ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            desativatela();
            limpatela();
            btnovo.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Clique em salvar para guardar os dados");
        }


    }//GEN-LAST:event_btcancelarActionPerformed

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
        Date data = new Date();
        SimpleDateFormat databr = new SimpleDateFormat("dd/MM/yyyy");

        tfdatacad.setText(databr.format(data));
        tfun.setText("UN");
        ativatela();
        flag = 1;
        btnovo.setEnabled(false);
        btsalvar.setEnabled(true);
    }//GEN-LAST:event_btnovoActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
        String produto = tfdescricao.getText();
        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Excluir o Item ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {

            prodcontrol.excluir(Integer.parseInt(tfcod.getText()));
            desativatela();
            limpatela();
            JOptionPane.showMessageDialog(rootPane, "Item " + produto + " Excluido com sucesso");
        } else {

        }
    }//GEN-LAST:event_btexcluirActionPerformed

    private void tfmargemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfmargemFocusLost
        if (!tfcusto.getText().equals("") && !tfmargem.getText().equals("")) {
            custo = (Double.parseDouble(tfcusto.getText().replace(",", ".")));
            margem = (Double.parseDouble(tfmargem.getText().replace(",", "."))) / 100;

            venda = custo + custo * margem;

            tfvenda.setText(dc.format(venda));
        }
    }//GEN-LAST:event_tfmargemFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoRadialProdutos;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btpesq;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlbreal;
    private javax.swing.JLabel jlbreal1;
    private javax.swing.JTextField tfcod;
    private javax.swing.JFormattedTextField tfcusto;
    private javax.swing.JTextField tfdatacad;
    private javax.swing.JTextField tfdescricao;
    private javax.swing.JFormattedTextField tfmargem;
    private javax.swing.JTextField tfpesq;
    private javax.swing.JFormattedTextField tfun;
    private javax.swing.JFormattedTextField tfvenda;
    // End of variables declaration//GEN-END:variables
public void desativatela() {
        tfdescricao.setEnabled(false);
        tfdatacad.setEnabled(false);
        tfcusto.setEnabled(false);
        tfvenda.setEnabled(false);
        tfmargem.setEnabled(false);
        tfun.setEnabled(false);
        btsalvar.setEnabled(false);
        btexcluir.setEnabled(false);
    }

    public void ativatela() {
        tfdescricao.setEnabled(true);
        tfdatacad.setEnabled(true);
        tfcusto.setEnabled(true);
        tfvenda.setEnabled(true);
        tfmargem.setEnabled(true);
        tfun.setEnabled(true);
    }

    public void limpatela() {
        tfcod.setText("");
        tfdescricao.setText("");
        tfdatacad.setText("");
        tfcusto.setText(null);
        tfvenda.setText(null);
        tfmargem.setText(null);
        tfun.setText("");
    }

    public void formun(JFormattedTextField jtf) {
        MaskFormatter formatoDois;
        try {
            formatoDois = new MaskFormatter("**");
            formatoDois.setValidCharacters("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789");
            formatoDois.install(jtf);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, this, "Não foi possivel inserir mask nos campos letras: "
                    + e.getMessage(), 0);
        }
    }

}
