/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import control.*;
import dao.OsDAO;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import model.Item;
import model.Os;
import model.Titulo;
import model.Usuario;
import model.Util;
import org.joda.time.Days;

/**
 *
 * @author Will
 */
public class OS extends javax.swing.JFrame {

    BufferedImage imagem;
    Buscapessoa buscap;
    int flag = 0;
    OSitem ositem;
    DecimalFormat dc;
    Date data = new Date();
    SimpleDateFormat dtbr = new SimpleDateFormat("dd/MM/yyyy");
    OsControl oscontrol = new OsControl();
    TituloControl tc = new TituloControl();
    boolean osig;
    boolean osg;
    boolean ostg;
    List<Item> exios;
    TitulosOs tos;

    public OS() {
        initComponents();
        desativaOS();
        formos();
        dc = new DecimalFormat("#0.00");
        exios = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        tabos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfcodos = new javax.swing.JTextField();
        tfcliente = new javax.swing.JTextField();
        tfdescricao = new javax.swing.JTextField();
        btpesqp = new javax.swing.JButton();
        tfcod = new javax.swing.JTextField();
        lbdescricao = new javax.swing.JLabel();
        lbcodcli = new javax.swing.JLabel();
        lbclifor = new javax.swing.JLabel();
        lbcodos = new javax.swing.JLabel();
        lbcodos1 = new javax.swing.JLabel();
        lbclifor2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfobs = new javax.swing.JTextArea();
        cbstatus = new javax.swing.JComboBox<>();
        lbclifor3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbcodos2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbcodcli1 = new javax.swing.JLabel();
        tfusuario = new javax.swing.JTextField();
        tftotalos = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfdtg = new com.toedter.calendar.JDateChooser();
        lbdescricao1 = new javax.swing.JLabel();
        lbcodcli2 = new javax.swing.JLabel();
        tfdtgd = new javax.swing.JFormattedTextField();
        tfdta = new com.toedter.calendar.JDateChooser();
        tfdtf = new com.toedter.calendar.JDateChooser();
        bttitulos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        btnovoitem = new javax.swing.JButton();
        bteditaritem = new javax.swing.JButton();
        btexcluiritem = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfsubtotal = new javax.swing.JFormattedTextField();
        tfdesconto = new javax.swing.JFormattedTextField();
        tftotal = new javax.swing.JFormattedTextField();
        btEnviar = new javax.swing.JPanel();
        btSelecionarImagem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfenviar = new javax.swing.JButton();
        lbimagem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfpesq = new javax.swing.JTextField();
        btpesqos = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btnovo = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        btcancelar = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ordem de Serviço");
        setResizable(false);

        tfcodos.setEditable(false);

        tfcliente.setEditable(false);

        btpesqp.setText("Pesquisar");
        btpesqp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqpActionPerformed(evt);
            }
        });

        tfcod.setEditable(false);

        lbdescricao.setText("Descrição Prod.*");

        lbcodcli.setText("Cod Cliente*");

        lbclifor.setText("Cliente*");

        lbcodos.setText("Cod O.S ");

        lbcodos1.setText("Data Abertura");

        lbclifor2.setText("Observações");

        tfobs.setColumns(20);
        tfobs.setRows(5);
        jScrollPane2.setViewportView(tfobs);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andamento", "Fechado" }));
        cbstatus.setEnabled(false);
        cbstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbstatusItemStateChanged(evt);
            }
        });
        cbstatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbstatusFocusGained(evt);
            }
        });
        cbstatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbstatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbstatusMouseExited(evt);
            }
        });
        cbstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusActionPerformed(evt);
            }
        });

        lbclifor3.setText("Status");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Valor Total O.S:");

        lbcodos2.setText("Data Fechamento");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("R$");

        lbcodcli1.setText("Usuário");

        tfusuario.setEditable(false);

        tftotalos.setEditable(false);
        tftotalos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tftotalos.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Campos obrigatórios marcados com *  para (Andamento) e ** para (Fechamento)");

        tfdtg.setEnabled(false);
        tfdtg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtgFocusLost(evt);
            }
        });
        tfdtg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfdtgMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfdtgMousePressed(evt);
            }
        });
        tfdtg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfdtgPropertyChange(evt);
            }
        });

        lbdescricao1.setText("Garantia até**");

        lbcodcli2.setText("Garantia (dias)");

        tfdtgd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfdtgd.setToolTipText("");
        tfdtgd.setDoubleBuffered(true);
        tfdtgd.setEnabled(false);
        tfdtgd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtgdFocusLost(evt);
            }
        });
        tfdtgd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfdtgdMouseExited(evt);
            }
        });

        tfdta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtaFocusLost(evt);
            }
        });
        tfdta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfdtaMouseExited(evt);
            }
        });

        tfdtf.setEnabled(false);
        tfdtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtfFocusLost(evt);
            }
        });
        tfdtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tfdtfMouseExited(evt);
            }
        });

        bttitulos.setText("Títulos");
        bttitulos.setEnabled(false);
        bttitulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttitulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tftotalos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbdescricao)
                                    .addComponent(lbcodos))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfcodos, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(lbcodos1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(lbcodos2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdtf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 43, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbcodcli1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbclifor3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbclifor2)
                                                .addGap(95, 95, 95))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbcodcli)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(lbcodcli2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(tfdtgd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbclifor)
                                            .addComponent(lbdescricao1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfdtg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btpesqp)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbstatus, 0, 100, Short.MAX_VALUE)
                                .addComponent(tfusuario))
                            .addComponent(bttitulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcodcli1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbclifor3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tfcodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbcodos)
                                        .addComponent(lbcodos1)
                                        .addComponent(lbcodos2))
                                    .addComponent(tfdta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbdescricao)))
                            .addComponent(tfdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfdtg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbdescricao1)
                                .addComponent(lbcodcli2)
                                .addComponent(tfdtgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbclifor)
                    .addComponent(tfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpesqp)
                    .addComponent(lbcodcli)
                    .addComponent(bttitulos))
                .addGap(58, 58, 58)
                .addComponent(lbclifor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftotalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabos.addTab("Ordem de Serviço", jPanel1);

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Quantidade", "UN", "Valor Unitário R$", "Valor Total Item R$", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItens.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblItens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblItens.getTableHeader().setResizingAllowed(false);
        tblItens.getTableHeader().setReorderingAllowed(false);
        tblItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItens);
        if (tblItens.getColumnModel().getColumnCount() > 0) {
            tblItens.getColumnModel().getColumn(0).setResizable(false);
            tblItens.getColumnModel().getColumn(1).setResizable(false);
            tblItens.getColumnModel().getColumn(2).setResizable(false);
            tblItens.getColumnModel().getColumn(3).setResizable(false);
            tblItens.getColumnModel().getColumn(4).setResizable(false);
        }

        btnovoitem.setText("Adicionar");
        btnovoitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoitemActionPerformed(evt);
            }
        });

        bteditaritem.setText("Editar");
        bteditaritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditaritemActionPerformed(evt);
            }
        });

        btexcluiritem.setText("Excluir");
        btexcluiritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluiritemActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("Total:       R$");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("SubTotal: R$");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("Desconto:   %");

        tfsubtotal.setEditable(false);
        tfsubtotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfsubtotal.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N

        tfdesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfdesconto.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tfdesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdescontoFocusLost(evt);
            }
        });

        tftotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tftotal.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tftotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tftotalFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnovoitem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bteditaritem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btexcluiritem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 442, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tftotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnovoitem)
                    .addComponent(bteditaritem)
                    .addComponent(btexcluiritem))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfsubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tabos.addTab("Itens", jPanel2);

        btSelecionarImagem.setText("Selecionar Imagem...");
        btSelecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarImagemActionPerformed(evt);
            }
        });

        jLabel8.setText("Imagem");

        tfenviar.setText("Enviar");
        tfenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfenviarActionPerformed(evt);
            }
        });

        lbimagem.setText(".");

        javax.swing.GroupLayout btEnviarLayout = new javax.swing.GroupLayout(btEnviar);
        btEnviar.setLayout(btEnviarLayout);
        btEnviarLayout.setHorizontalGroup(
            btEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGroup(btEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btEnviarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btEnviarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btSelecionarImagem)
                        .addGap(18, 18, 18)
                        .addComponent(tfenviar)))
                .addContainerGap(514, Short.MAX_VALUE))
        );
        btEnviarLayout.setVerticalGroup(
            btEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btSelecionarImagem)
                    .addComponent(tfenviar))
                .addGap(29, 29, 29)
                .addComponent(lbimagem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        tabos.addTab("Galeria", btEnviar);

        jLabel9.setText("Pesquisar O.S (Descrição)");

        tfpesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpesqKeyPressed(evt);
            }
        });

        btpesqos.setText("Pesquisar");
        btpesqos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqosActionPerformed(evt);
            }
        });

        btnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/user.png"))); // NOI18N
        btnovo.setText("Novo");
        btnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnovoActionPerformed(evt);
            }
        });

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        btcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btcancelar.setText("Cancelar");
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        btsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield-1.png"))); // NOI18N
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btpesqos)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnovo)
                        .addGap(10, 10, 10)
                        .addComponent(btsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btcancelar)
                        .addContainerGap())))
            .addComponent(tabos)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btpesqos)
                    .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabos, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnovo)
                    .addComponent(btexcluir)
                    .addComponent(btcancelar)
                    .addComponent(btsalvar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void limpaos() {
        tftotal.setText("");
        tftotalos.setText("");
        tfsubtotal.setText("");
        tfdesconto.setText("");
        tfcodos.setText("");
        tfcod.setText("");
        tfusuario.setText("");
        tfcliente.setText("");
        tfdescricao.setText("");
        tfobs.setText("");
        tfdta.setDate(null);
        tfdtf.setDate(null);
        tfdtg.setDate(null);
        cbstatus.setSelectedIndex(0);
        DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
        t.setNumRows(0);
        exios.clear();

    }

    private void desativaOS() {
        btsalvar.setEnabled(false);
        btexcluir.setEnabled(false);
        tabos.setEnabledAt(1, false);
        tabos.setEnabledAt(2, false);
        tfdescricao.setEnabled(false);
        cbstatus.setEnabled(false);
        btpesqp.setEnabled(false);
        btnovo.setEnabled(true);
        tfdtg.setEnabled(false);
        tfdta.setEnabled(false);
        tfdtgd.setEnabled(false);
        tabos.setSelectedIndex(0);
        bttitulos.setEnabled(false);
    }

    private void ativaOS() {
        btsalvar.setEnabled(true);
        btnovo.setEnabled(false);
        tabos.setEnabledAt(1, true);
        //tabos.setEnabledAt(2, true);
        tfdescricao.setEnabled(true);
        //    cbstatus.setEnabled(true);
        btpesqp.setEnabled(true);
        //  tfdtg.setEnabled(true);
        //  tfdtgd.setEnabled(true);
    }

    private void ut() {

        DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
        int ul = t.getRowCount();
        double subtotal = 0;
        double desconto = Double.parseDouble(tfdesconto.getText().replace(",", "."));

        for (int l = 0; l < ul; l++) {

            subtotal += Double.parseDouble(t.getValueAt(l, 4).toString());

        }
        double descfinal = desconto * subtotal / 100;

        tfsubtotal.setText(String.valueOf(dc.format(subtotal)));
        tftotal.setText(String.valueOf(dc.format(subtotal - descfinal)));
        tftotalos.setText(String.valueOf(dc.format(subtotal - descfinal)));

    }


    private void btSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarImagemActionPerformed
        JFileChooser jf = new JFileChooser();
        int res = jf.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = jf.getSelectedFile();

            try {

                //            imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(),160,160);
                lbimagem.setIcon(new ImageIcon(imagem));
            } catch (Exception ex) {

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Você não selecionou uma imagem!");
        }
    }//GEN-LAST:event_btSelecionarImagemActionPerformed

    private void tfenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfenviarActionPerformed
        try {
            String caminho = getClass().getResource("../imagens/").toString().substring(3);
            JOptionPane.showMessageDialog(rootPane, caminho);
            File outputfile = new File(caminho + "image.jpg");
            ImageIO.write(imagem, "jpg", outputfile);
            JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso!");
        } catch (IOException ex) {
            Logger.getLogger(OS.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tfenviarActionPerformed

    private void btpesqosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqosActionPerformed
        limpaos();
        desativaOS();
        Buscaos buscaos;
        buscaos = new Buscaos(this, true, tfpesq.getText());
        buscaos.setVisible(true);
        try {

            tfcodos.setText(String.valueOf(buscaos.o.getCod()));
            tfdta.setDate(Util.dataBR(buscaos.o.getDta()));
            tfdtf.setDate(Util.dataBR(buscaos.o.getDtf()));
            tfdtg.setDate(Util.dataBR(buscaos.o.getDtg()));
            tfusuario.setText(buscaos.o.getUseros());
            tfdescricao.setText(buscaos.o.getDescricao());
            tfcod.setText(String.valueOf(buscaos.o.getCodclifor()));
            tfcliente.setText(buscaos.o.getClifor());
            tfdesconto.setText(String.valueOf(buscaos.o.getDesconto()));
            cbstatus.setSelectedItem(buscaos.o.getStatus());
            tfobs.setText(buscaos.o.getObs());

            int ul = buscaos.itens.size();

            for (int l = 0; l < ul; l++) {
                DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
                Item i = buscaos.itens.get(l);

                t.addRow(new Object[]{i.getDescricao(), i.getQtd(), i.getUN(),
                    i.getVenda(), i.getTotalitem(), i.getId()});

            }

            ativaOS();
            ut();
            flag = 2;
            tfpesq.setText("");
            cbstatus.setEnabled(true);
            if (buscaos.o.getStatus().equals("Fechado")) {
                btsalvar.setEnabled(false);
                btnovoitem.setEnabled(false);
                bteditaritem.setEnabled(false);
                btexcluiritem.setEnabled(false);
                btpesqp.setEnabled(false);
                cbstatus.setEnabled(false);
                tfdtg.setEnabled(false);
                tfdtgd.setEnabled(false);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Nenhuma O.S Selecionada");
            tfpesq.setText("");
            tfcodos.setText("");
        }

    }//GEN-LAST:event_btpesqosActionPerformed

    private void btpesqpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqpActionPerformed

        buscap = new Buscapessoa(this, true, "abrir", 0);
        buscap.setVisible(true);

        tfcod.setText(String.valueOf(buscap.p.getCodpessoa()));
        tfcliente.setText(buscap.p.getNome());


    }//GEN-LAST:event_btpesqpActionPerformed

    private void btnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoActionPerformed
//        Usuario u = new Usuario();
//        u.setNome("Admin");
//        Util.usuario = u;

        tfdesconto.setText("0,00");
        ativaOS();
        cbstatus.setSelectedItem("Andamento");
        tfusuario.setText(Util.usuario.getNome());
        tfdta.setDate(data);
        btnovoitem.setEnabled(true);
        bteditaritem.setEnabled(true);
        btexcluiritem.setEnabled(true);

        flag = 1;

    }//GEN-LAST:event_btnovoActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed
    }//GEN-LAST:event_btexcluirActionPerformed

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Cancelar (As Alterações realizadas serão perdidas se não clicar em salvar) ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            limpaos();
            desativaOS();
            bttitulos.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Clique em salvar para guardar os dados");
        }

    }//GEN-LAST:event_btcancelarActionPerformed

    private void btnovoitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnovoitemActionPerformed
        if (tos == null) {

        } else {
            tos.titos.clear();
        }

        ositem = new OSitem(null, true, false);
        ositem.setVisible(true);
        if (flag == 1) {
            if (ositem.i.isFechado()) {

            } else {
                DefaultTableModel t = (DefaultTableModel) tblItens.getModel();

                t.addRow(new Object[]{ositem.i.getDescricao(), ositem.i.getQtd(), ositem.i.getUN(),
                    ositem.i.getVenda(), ositem.i.getTotalitem()});
                ut();
            }
        }
        if (flag == 2) {
            if (ositem.i.isFechado()) {

            } else {
                DefaultTableModel t = (DefaultTableModel) tblItens.getModel();

                t.addRow(new Object[]{ositem.i.getDescricao(), ositem.i.getQtd(), ositem.i.getUN(),
                    ositem.i.getVenda(), ositem.i.getTotalitem(), 0});
                ut();

            }
        }


    }//GEN-LAST:event_btnovoitemActionPerformed

    private void btexcluiritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluiritemActionPerformed
        if (tos == null) {

        } else {
            tos.titos.clear();
        }
        if (flag == 1) {
            if (tblItens.getSelectedRow() >= 0) {
                DefaultTableModel t = (DefaultTableModel) tblItens.getModel();

                t.removeRow(tblItens.getSelectedRow());
                ut();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um item para excluir");
            }
        }
        if (flag == 2) {
            if (tblItens.getSelectedRow() >= 0) {
                DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
                Item i = new Item();
                i.setCodproduto(Integer.parseInt(t.getValueAt(tblItens.getSelectedRow(), 5).toString()));
                exios.add(i);
                t.removeRow(tblItens.getSelectedRow());
                ut();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um item para excluir");
            }
        }

    }//GEN-LAST:event_btexcluiritemActionPerformed

    private void bteditaritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditaritemActionPerformed
        if (tos == null) {

        } else {
            tos.titos.clear();
        }

        if (tblItens.getSelectedRow() >= 0) {
            int l = tblItens.getSelectedRow();
            ositem = new OSitem(null, true, true);

            DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
            Item i = new Item();
            i.setDescricao(t.getValueAt(l, 0).toString());
            i.setQtd(Double.parseDouble(t.getValueAt(l, 1).toString()));
            i.setUN(t.getValueAt(l, 2).toString());
            i.setVenda(Double.parseDouble(t.getValueAt(l, 3).toString()));
            i.setTotalitem(Double.parseDouble(t.getValueAt(l, 4).toString()));

            ositem.rv(i);
            ositem.setVisible(true);
            if (ositem.i.isFechado()) {

            } else {
                t.setValueAt(ositem.i.getDescricao(), l, 0);
                t.setValueAt(ositem.i.getQtd(), l, 1);
                t.setValueAt(ositem.i.getUN(), l, 2);
                t.setValueAt(ositem.i.getVenda(), l, 3);
                t.setValueAt(ositem.i.getTotalitem(), l, 4);
                ut();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Item para editar");
        }

    }//GEN-LAST:event_bteditaritemActionPerformed

    private void tblItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensMouseClicked
        if (evt.getClickCount() == 2) {
            bteditaritem.doClick();
        }

    }//GEN-LAST:event_tblItensMouseClicked

    private void tfdescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdescontoFocusLost
        if (tfdesconto.getText().equals("")) {
            tfdesconto.setText("0,00");
        }
        ut();

    }//GEN-LAST:event_tfdescontoFocusLost

    private void cbstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbstatusItemStateChanged


    }//GEN-LAST:event_cbstatusItemStateChanged

    private void tftotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftotalFocusLost
        double subtotal = Double.parseDouble(tfsubtotal.getText().replace(",", "."));
        double total = Double.parseDouble(tftotal.getText().replace(",", "."));

        double dfinal = subtotal - total;
        double dfinal2 = dfinal / subtotal * 100;
        tfdesconto.setText(dc.format(dfinal2));

    }//GEN-LAST:event_tftotalFocusLost

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        if (!tfcod.getText().isEmpty() && cbstatus.getSelectedIndex() == 1) {
            if (tfdtg.getDate() == null) {

            } else if (Util.vdtg(tfdta.getDate(), tfdtg.getDate())) {

            } else {
                JOptionPane.showMessageDialog(rootPane, "A data da garantia tem que ser maior que a data de abertura");
                tfdtg.setDate(null);
                tfdtg.requestFocus();
            }

        }
        if (tos == null) {
            Titulo t = new Titulo();
            t.setId(-1);
            tos = new view.TitulosOs(this, true, t, 1);
        }

        if (cbstatus.getSelectedIndex() == 0) {
            if (tfdescricao.getText().isEmpty() || tfcliente.getText().isEmpty() || tblItens.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Preencha os campos obrigatórios! A O.S deve ter pelo menos um Item");
            } else {
                tfdtf.setDate(null);
                tfdtg.setDate(null);
                salvaros();
            }
        } else if (cbstatus.getSelectedIndex() == 1) {

            if (tfdescricao.getText().isEmpty() || tfcliente.getText().isEmpty()
                    || tblItens.getRowCount() == 0 || tfdtg.getDate() == null || tos.titos.isEmpty()) {

                JOptionPane.showMessageDialog(rootPane,
                        "Preencha os campos obrigatórios!\n "
                        + "A O.S deve ter pelo menos um Item!\n "
                        + "Preencha a data da garantia!\n"
                        + "Os Titulos devem ser gerados");
            } else {

                salvaros();
            }
        }


    }//GEN-LAST:event_btsalvarActionPerformed

    private void tfdtgdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtgdFocusLost
        try {
            Calendar calend = Calendar.getInstance();
            calend.setTime(tfdtf.getDate());

            calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + Integer.parseInt(tfdtgd.getText()));

            tfdtg.setDate(Util.dataBR(dtbr.format(calend.getTime())));
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_tfdtgdFocusLost

    private void tfdtgdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdtgdMouseExited


    }//GEN-LAST:event_tfdtgdMouseExited

    private void tfdtgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtgFocusLost


    }//GEN-LAST:event_tfdtgFocusLost

    private void tfdtgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdtgMouseExited

    }//GEN-LAST:event_tfdtgMouseExited

    private void tfdtaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtaFocusLost

    private void tfdtaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdtaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtaMouseExited

    private void tfdtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtfFocusLost

    private void tfdtfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdtfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdtfMouseExited

    private void tfdtgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfdtgMousePressed

    }//GEN-LAST:event_tfdtgMousePressed

    private void tfdtgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfdtgPropertyChange

        tfdtgd.setText(String.valueOf(calcdias()));


    }//GEN-LAST:event_tfdtgPropertyChange

    private void bttitulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttitulosActionPerformed
        if (btsalvar.isEnabled()) {
            tfdtf.setDate(data);
            Titulo t = new Titulo();
            t.setDoc(Integer.parseInt(tfcodos.getText()));
            t.setDte(Util.datatoStringBR(tfdtf.getDate()));
            t.setIdclifor(Integer.parseInt(tfcod.getText()));
            t.setClifor(tfcliente.getText());
            t.setVlrtotal(Double.parseDouble(tftotalos.getText().replace(",", ".")));
            t.setDescos("Ref. O.S cod " + tfcodos.getText());
            tos = new view.TitulosOs(this, true, t, 1);

            tos.setVisible(true);
        } else {
            Titulo t = new Titulo();
            t.setIdclifor(Integer.parseInt(tfcod.getText()));
            t.setDoc(Integer.parseInt(tfcodos.getText()));
            tos = new view.TitulosOs(this, true, t, 2);
            tos.setVisible(true);
        }


    }//GEN-LAST:event_bttitulosActionPerformed

    private void tfpesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btpesqos.doClick();

        }
    }//GEN-LAST:event_tfpesqKeyPressed

    private void cbstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusActionPerformed
//        if (cbstatus.getSelectedIndex() == 0 & tfcodos.getText().isEmpty()) {
//            cbstatus.setSelectedIndex(0);
//            JOptionPane.showMessageDialog(rootPane, "Para fechar uma O.S primeiro salvea com status 'andamento'");
//
//        }

        if (cbstatus.getSelectedIndex() == 1 & !tfcodos.getText().isEmpty()) {
            if (cbstatus.getSelectedIndex() == 0) {
                tfdtf.setDate(null);
                tfdtg.setEnabled(false);
                tfdtgd.setEnabled(false);
                bttitulos.setEnabled(false);
            }
            if (cbstatus.getSelectedIndex() == 1) {
                tfdtg.setEnabled(true);
                tfdtgd.setEnabled(true);
                bttitulos.setEnabled(true);
            }
        }
//        tfdtg.setEnabled(false);
//        tfdtgd.setEnabled(false);
//        tfdtf.setEnabled(false);
//        bttitulos.setEnabled(false);
//        tfdtf.setDate(null);
//        tfdtg.setDate(null);
//        tfdtgd.setText(null);
    }//GEN-LAST:event_cbstatusActionPerformed

    private void cbstatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbstatusMouseExited


    }//GEN-LAST:event_cbstatusMouseExited

    private void cbstatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbstatusMouseEntered

    }//GEN-LAST:event_cbstatusMouseEntered

    private void cbstatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbstatusFocusGained

    }//GEN-LAST:event_cbstatusFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btEnviar;
    private javax.swing.JButton btSelecionarImagem;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton bteditaritem;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btexcluiritem;
    private javax.swing.JButton btnovo;
    private javax.swing.JButton btnovoitem;
    private javax.swing.JButton btpesqos;
    private javax.swing.JButton btpesqp;
    private javax.swing.JButton btsalvar;
    private javax.swing.JButton bttitulos;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbclifor;
    private javax.swing.JLabel lbclifor2;
    private javax.swing.JLabel lbclifor3;
    private javax.swing.JLabel lbcodcli;
    private javax.swing.JLabel lbcodcli1;
    private javax.swing.JLabel lbcodcli2;
    private javax.swing.JLabel lbcodos;
    private javax.swing.JLabel lbcodos1;
    private javax.swing.JLabel lbcodos2;
    private javax.swing.JLabel lbdescricao;
    private javax.swing.JLabel lbdescricao1;
    private javax.swing.JLabel lbimagem;
    private javax.swing.JTabbedPane tabos;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField tfcliente;
    private javax.swing.JTextField tfcod;
    private javax.swing.JTextField tfcodos;
    private javax.swing.JFormattedTextField tfdesconto;
    private javax.swing.JTextField tfdescricao;
    private com.toedter.calendar.JDateChooser tfdta;
    private com.toedter.calendar.JDateChooser tfdtf;
    private com.toedter.calendar.JDateChooser tfdtg;
    private javax.swing.JFormattedTextField tfdtgd;
    private javax.swing.JButton tfenviar;
    private javax.swing.JTextArea tfobs;
    private javax.swing.JTextField tfpesq;
    private javax.swing.JFormattedTextField tfsubtotal;
    private javax.swing.JFormattedTextField tftotal;
    private javax.swing.JFormattedTextField tftotalos;
    private javax.swing.JTextField tfusuario;
    // End of variables declaration//GEN-END:variables
private void formos() {
        tblItens.getColumnModel().getColumn(0).setPreferredWidth(300);
        tblItens.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblItens.getColumnModel().getColumn(2).setPreferredWidth(70);
        tblItens.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblItens.getColumnModel().getColumn(4).setPreferredWidth(150);
        tblItens.removeColumn(tblItens.getColumnModel().getColumn(5));
    }

    private int calcdias() {
        try {
            int dias = Days.daysBetween(Util.DateToDTM(tfdtf.getDate()),
                    Util.DateToDTM(tfdtg.getDate())).getDays();

            return dias;
        } catch (Exception ex) {
            printStackTrace(ex);
            return 0;

        }

    }

    private void salvaros() {
        Os o = new Os();

        o.setDta(Util.datatoStringUS(tfdta.getDate()));
        o.setDtf(Util.datatoStringUS(tfdtf.getDate()));
        o.setDtg(Util.datatoStringUS(tfdtg.getDate()));
        o.setUseros(tfusuario.getText());
        o.setDescricao(tfdescricao.getText());
        o.setStatus(cbstatus.getSelectedItem().toString());
        o.setCodclifor(Integer.parseInt(tfcod.getText()));
        o.setClifor(tfcliente.getText());
        o.setObs(tfobs.getText());
        o.setSubtotal(Double.parseDouble(tfsubtotal.getText().replace(",", ".")));
        o.setDesconto(Double.parseDouble(tfdesconto.getText().replace(",", ".")));
        o.setTotal(Double.parseDouble(tftotal.getText().replace(",", ".")));

        Item i = new Item();
        OsDAO osdao = new OsDAO();

        if (flag == 1) {
            osg = oscontrol.salvar(o);
            i = osdao.lastid();

        }
        if (flag == 2) {
            o.setCod(Integer.parseInt(tfcodos.getText()));
            osg = oscontrol.alterar(o);
            if (tos.titos.size() > 0) {

                for (int tt = 0; tt < tos.titos.size(); tt++) {

                    ostg = tc.salvar(tos.titos.get(tt));

                }

            }

        }
        DefaultTableModel t = (DefaultTableModel) tblItens.getModel();
        int ul = t.getRowCount();
        int codos = i.getCodos();
        for (int l = 0; l < ul; l++) {

            i.setCodos(codos);
            i.setDescricao(t.getValueAt(l, 0).toString());
            i.setQtd(Double.parseDouble(t.getValueAt(l, 1).toString()));
            i.setUN(t.getValueAt(l, 2).toString());
            i.setVenda(Double.parseDouble(t.getValueAt(l, 3).toString()));
            i.setTotalitem(Double.parseDouble(t.getValueAt(l, 4).toString()));
            if (flag == 2) {
                i.setId(Integer.parseInt(t.getValueAt(l, 5).toString()));
            }
            if (flag == 1) {
                osig = oscontrol.salvaritensos(i);
            }
            if (flag == 2 && i.getId() != 0) {
                osig = oscontrol.alteraritensos(i);
            }
            if (i.getId() == 0 && flag == 2) {
                i.setCodos(Integer.parseInt(tfcodos.getText()));
                osig = oscontrol.salvaritensos(i);
            }
        }
        if (flag == 2 && exios.size() > 0) {
            try {
                int ule = exios.size();
                for (int l = 0; l < ule; l++) {
                    Item ix = exios.get(l);
                    oscontrol.removeritensos(ix.getCodproduto());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir itens removidos da O.S");
            }

        }
        if (flag == 1 | flag == 2) {
            if (osg && osig) {
                JOptionPane.showMessageDialog(rootPane, "Dados Gravados com sucesso");
                limpaos();
                desativaOS();
                flag = 0;
            }
        }

        if (flag == 2 && tos.titos.size() > 0) {
            if (osg && osig && ostg) {
                JOptionPane.showMessageDialog(rootPane, "Dados Gravados com sucesso. A O.S foi Fechada ");
                limpaos();
                desativaOS();
                flag = 0;
            }
        }

    }

}
