/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ItemControl;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.Item;

/**
 *
 * @author Will
 */
public class OSitem extends javax.swing.JDialog {

    Buscaitem buscaprod;
    Double custo;
    Double margem;
    Double venda;
    Double qtd;
    Double marg;
    Double sub;
    DecimalFormat dc;
    Item i = new Item();
    boolean editar;
    ItemControl icontrol = new ItemControl();

    /**
     * Creates new form OSitem
     *
     * @param parent
     * @param modal
     * @param editando
     */
    public OSitem(java.awt.Frame parent, boolean modal, boolean editando) {
        super(parent, modal);
        initComponents();
        MaskFormatter formatoDois;

        try {
            formatoDois = new MaskFormatter("**");
            formatoDois.setValidCharacters("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789");
            formatoDois.install(tfun);
        } catch (ParseException ex) {
            Logger.getLogger(OSitem.class.getName()).log(Level.SEVERE, null, ex);
        }
        tfun.setText("UN");
        tfqtd.setText("1");
        dc = new DecimalFormat("#0.00");

        editar = editando;
        i.setFechado(true);
        if (editando) {

        }

        //("#.##");
        //("#,###.00")
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        tfcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btpesq = new javax.swing.JButton();
        btok = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfun = new javax.swing.JFormattedTextField();
        tfqtd = new javax.swing.JFormattedTextField();
        tfcusto = new javax.swing.JFormattedTextField();
        tfmargem = new javax.swing.JFormattedTextField();
        tftotitem = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfvenda = new javax.swing.JFormattedTextField();
        btsalvaritem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Item OS");
        setName("Iten OS"); // NOI18N
        setResizable(false);

        jLabel7.setText("UN*");

        tfcod.setEnabled(false);

        jLabel2.setText("Cod Interno");

        jLabel3.setText("Descrição*");

        btpesq.setText("Pesquisar");
        btpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqActionPerformed(evt);
            }
        });

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        jLabel13.setText("Custo*");

        jLabel20.setText("Lucro* %");

        jLabel15.setText("Venda Unitário*");

        jLabel14.setText("Quantidade*");

        jLabel16.setText("Total Item");

        tfqtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfqtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfqtdFocusLost(evt);
            }
        });

        tfcusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfcusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcustoFocusLost(evt);
            }
        });

        tfmargem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfmargem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfmargemFocusLost(evt);
            }
        });

        tftotitem.setEditable(false);
        tftotitem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Campos obrigatórios marcados com *");

        tfvenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfvenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfvendaFocusLost(evt);
            }
        });

        btsalvaritem.setText("Salvar Item");
        btsalvaritem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvaritemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsalvaritem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfcusto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(tfvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfmargem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tftotitem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel14)
                            .addComponent(tfqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(tfcusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(tfvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfmargem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tftotitem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btok)
                    .addComponent(btsalvaritem))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void rv(Item i) {
        tfdescricao.setText(i.getDescricao());
        tfqtd.setText(i.getQtd().toString());
        tfun.setText(i.getUN());
        tfvenda.setText(i.getVenda().toString());
        tftotitem.setText(i.getTotalitem().toString());

    }


    private void btpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqActionPerformed

        buscaprod = new Buscaitem(null, true, tfdescricao.getText());
        buscaprod.setVisible(true);
        if (buscaprod.p.getCodproduto() > 0) {
            tfcod.setText(String.valueOf(buscaprod.p.getCodproduto()));
            tfdescricao.setText(buscaprod.p.getDescricao());
            tfcusto.setText(String.valueOf(buscaprod.p.getCusto()));
            tfvenda.setText(String.valueOf(buscaprod.p.getVenda()));
            tfmargem.setText(String.valueOf(buscaprod.p.getLucro()));
            tfun.setText(String.valueOf(buscaprod.p.getUN()));
            atualizacampos();
        }


    }//GEN-LAST:event_btpesqActionPerformed

    private void tfqtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfqtdFocusLost
        if (!tfqtd.getText().equals("")) {
            if (Double.parseDouble(tfqtd.getText().replace(",", ".")) == 0) {
                tfqtd.setText("1");
            }
        }

        if (!tfvenda.getText().equals("") && !tfqtd.getText().equals("")) {
            qtd = Double.parseDouble(tfqtd.getText().replace(",", "."));
            venda = Double.parseDouble(tfvenda.getText().replace(",", "."));

            tftotitem.setText(dc.format(venda * qtd));
        }
    }//GEN-LAST:event_tfqtdFocusLost

    private void tfmargemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfmargemFocusLost

        if (!tfcusto.getText().equals("") && !tfmargem.getText().equals("")) {
            custo = (Double.parseDouble(tfcusto.getText().replace(",", ".")));
            margem = (Double.parseDouble(tfmargem.getText().replace(",", "."))) / 100;

            venda = custo + custo * margem;
            tfvenda.setText(dc.format(venda));
        }
        if (!tfvenda.getText().equals("") && !tfqtd.getText().equals("")) {
            qtd = Double.parseDouble(tfqtd.getText().replace(",", "."));
            tftotitem.setText(String.valueOf(dc.format(Double.parseDouble(tfvenda.getText().replace(",", ".")) * qtd)));
        }
        if (tfmargem.getText().isEmpty()) {
            tfmargem.setText("45,00");
        }
    }//GEN-LAST:event_tfmargemFocusLost

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed

        if (tfdescricao.getText().equals("") || tfqtd.getText().equals("") || tfun.getText().equals("")
                || tfvenda.getText().equals("") ) {
            JOptionPane.showMessageDialog(rootPane, "Escolha um item em 'pesquisar' ou preencha os campos obrigatórios!");
        } else {
            i.setDescricao(tfdescricao.getText());
            i.setQtd(Double.parseDouble(tfqtd.getText().replace(",", ".")));
            i.setUN(tfun.getText());
            i.setVenda(Double.parseDouble(tfvenda.getText().replace(",", ".")));
//            i.setCusto(Double.parseDouble(tfcusto.getText().replace(",", ".")));
            i.setTotalitem(Double.parseDouble(tftotitem.getText().replace(",", ".")));
//            i.setLucro(Double.parseDouble(tftotitem.getText().replace(",", ".")));
            i.setFechado(false);
            this.dispose();

        }
    }//GEN-LAST:event_btokActionPerformed

    private void tfvendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfvendaFocusLost
        if (!tfcusto.getText().equals("") && !tfvenda.getText().equals("")) {
            qtd = Double.parseDouble(tfqtd.getText().replace(",", "."));
            venda = Double.parseDouble(tfvenda.getText().replace(",", "."));
            custo = Double.parseDouble(tfcusto.getText().replace(",", "."));
            sub = venda - custo;
            marg = sub / custo * 100;
            tfmargem.setText(String.valueOf(dc.format(marg)));

        }
        if (!tfqtd.getText().equals("") && !tfvenda.getText().equals("")) {
            qtd = Double.parseDouble(tfqtd.getText().replace(",", "."));
            venda = Double.parseDouble(tfvenda.getText().replace(",", "."));

            tftotitem.setText(dc.format(venda * qtd));
        }

    }//GEN-LAST:event_tfvendaFocusLost

    private void tfcustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcustoFocusLost
        if (tfcusto.getText().isEmpty()) {
            tfcusto.setText("0,15");
        }
    }//GEN-LAST:event_tfcustoFocusLost

    private void btsalvaritemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvaritemActionPerformed
        if (tfdescricao.getText().equals("") || tfqtd.getText().equals("") || tfun.getText().equals("")
                || tfvenda.getText().equals("") || tfmargem.getText().isEmpty() || tfcusto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Escolha um item em 'pesquisar' ou preencha os campos obrigatórios!");
        } else {
            int reply = JOptionPane.showConfirmDialog(null, "Deseja Cadastrar o Item ", "Cadastrar?", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                i.setDescricao(tfdescricao.getText());
                i.setQtd(Double.parseDouble(tfqtd.getText().replace(",", ".")));
                i.setUN(tfun.getText());
                i.setVenda(Double.parseDouble(tfvenda.getText().replace(",", ".")));
                i.setCusto(Double.parseDouble(tfcusto.getText().replace(",", ".")));
                i.setTotalitem(Double.parseDouble(tftotitem.getText().replace(",", ".")));
                i.setLucro(Double.parseDouble(tftotitem.getText().replace(",", ".")));
                i.setFechado(false);
                Date data = new Date();
                SimpleDateFormat databr = new SimpleDateFormat("yyyy/MM/dd");
                i.setDatacad(databr.format(data));
                if (icontrol.salvar2(i)) {
                    JOptionPane.showMessageDialog(rootPane, "Item cadastrado com Sucesso");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar item");
                }
                this.dispose();
            } else {

            }
        }
    }//GEN-LAST:event_btsalvaritemActionPerformed

    private void atualizacampos() {
        qtd = Double.parseDouble(tfqtd.getText().replace(",", "."));
        venda = Double.parseDouble(tfvenda.getText().replace(",", "."));
        custo = Double.parseDouble(tfcusto.getText().replace(",", "."));
        margem = Double.parseDouble(tfmargem.getText().replace(",", ".")) / 100;
        tftotitem.setText(dc.format(venda * qtd));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OSitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OSitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OSitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OSitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OSitem dialog = new OSitem(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btok;
    private javax.swing.JButton btpesq;
    private javax.swing.JButton btsalvaritem;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tfcod;
    private javax.swing.JFormattedTextField tfcusto;
    private javax.swing.JTextField tfdescricao;
    private javax.swing.JFormattedTextField tfmargem;
    private javax.swing.JFormattedTextField tfqtd;
    private javax.swing.JFormattedTextField tftotitem;
    private javax.swing.JFormattedTextField tfun;
    private javax.swing.JFormattedTextField tfvenda;
    // End of variables declaration//GEN-END:variables
}
