/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.OsControl;
import control.TituloControl;
import dao.ConfigDAO;
import dao.OsDAO;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import model.Util;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.TreeNode;
import model.Config;
import model.Os;
import org.joda.time.Days;
import java.util.Timer;
import model.Titulo;

/**
 *
 * @author Will-Not
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    OsControl oscontrol;
    TituloControl tcontrol;

    public Principal() {
        initComponents();
        oscontrol = new OsControl();
        tcontrol = new TituloControl();
        tfdtfi.setEnabled(false);
        tfdtff.setEnabled(false);

        lbuseron.setText(Util.usuario.getNome());
        popdata();
        calcdata();
        populaosg();
        populaospesqp();
        populatspesqp();

        if (!Util.usuario.isOs()) {
            jtp.setEnabledAt(0, false);
            jtp.setEnabledAt(1, false);
            DefaultTableModel t = (DefaultTableModel) tbgos.getModel();
            t.setNumRows(0);
        }
        if (!Util.usuario.isAreceber()) {
            jtp.setEnabledAt(2, false);
            DefaultTableModel t = (DefaultTableModel) tbt.getModel();
            t.setNumRows(0);
        }
        if (Util.usuario.isOs() | Util.usuario.isAreceber()) {
            Timer timer = null;
            long TEMPO = (1000 * 5); // chama o método a cada 5 segundos 
            if (timer == null) {
                timer = new Timer();
                TimerTask tarefa = new TimerTask() {
                    @Override
                    public void run() {
                        try {
                            if (Util.usuario.isOs()) {
                                populaosg();
                                populaospesqp();
                            }
                            if (Util.usuario.isAreceber()) {
                                populatspesqp();
                            }

                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }
                };
                timer.scheduleAtFixedRate(tarefa, TEMPO, TEMPO);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        lbuseron = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbgos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbcdias = new javax.swing.JLabel();
        btconfig = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbosp = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tftotalos = new javax.swing.JFormattedTextField();
        cbstatus = new javax.swing.JComboBox<>();
        tfdtfi = new com.toedter.calendar.JDateChooser();
        tfdtff = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btpesqosp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbt = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfdtvi = new com.toedter.calendar.JDateChooser();
        tfdtvf = new com.toedter.calendar.JDateChooser();
        lbcdias3 = new javax.swing.JLabel();
        lbcdias4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tftotalts = new javax.swing.JFormattedTextField();
        cbtipo = new javax.swing.JComboBox<>();
        tfdtbi = new com.toedter.calendar.JDateChooser();
        lbcdias5 = new javax.swing.JLabel();
        lbcdias6 = new javax.swing.JLabel();
        tfdtbf = new com.toedter.calendar.JDateChooser();
        btpesqt = new javax.swing.JButton();
        cbbaixado = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Menu");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastros");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Pessoas/Fornecedores/Usuários");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Itens");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Ordem de Serviço");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("O.S");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Títulos");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("A Receber/ A Pagar");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        menu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
                teste(evt);
            }
        });
        jScrollPane1.setViewportView(menu);

        lbuseron.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbuseron.setForeground(new java.awt.Color(0, 169, 42));
        lbuseron.setText("userON");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Usuário Atual:");

        tbgos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. O.S", "Descrição Produto", "Dias Restantes Garantia", "Garantia Até"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbgos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbgos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbgos);

        jLabel2.setText("Notificando:");

        lbcdias.setText("cdias");

        btconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/settings.png"))); // NOI18N
        btconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btconfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbcdias))
                    .addComponent(btconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(353, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbcdias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btconfig)
                .addContainerGap())
        );

        jtp.addTab("Garantia", jPanel1);

        tbosp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. O.S", "Descrição Produto", "Data Abertura", "Cliente", "Valor R$", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbosp.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbosp.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbosp);

        jLabel4.setText("Status:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("R$");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Valor total no período");

        tftotalos.setEditable(false);
        tftotalos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tftotalos.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andamento", "Fechado" }));
        cbstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbstatusItemStateChanged(evt);
            }
        });
        cbstatus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbstatusPropertyChange(evt);
            }
        });

        tfdtfi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtfiFocusLost(evt);
            }
        });

        tfdtff.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdtffFocusLost(evt);
            }
        });

        jLabel6.setText("Data Fechamento:");

        jLabel7.setText("Final");

        jLabel8.setText("Inicial");

        btpesqosp.setText("Pesquisar");
        btpesqosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqospActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tfdtfi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tftotalos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfdtff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btpesqosp)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tftotalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfdtfi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfdtff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btpesqosp))
        );

        jtp.addTab("O.S", jPanel2);

        tbt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente/Fornecedor", "Parcela", "Vencimento", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbt.setToolTipText("");
        tbt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbt.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbt);

        jLabel5.setText("Tipo:");

        lbcdias3.setText("Vencimento (inicial)");

        lbcdias4.setText("Vencimento (final)");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setText("R$");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Valor total no período");

        tftotalts.setEditable(false);
        tftotalts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tftotalts.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Receber", "A Pagar" }));
        cbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbtipoItemStateChanged(evt);
            }
        });
        cbtipo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbtipoPropertyChange(evt);
            }
        });

        tfdtbi.setEnabled(false);

        lbcdias5.setText("Dt Baixa (inicial)");

        lbcdias6.setText("Dt Baixa (final)");

        tfdtbf.setEnabled(false);

        btpesqt.setText("Pesquisar");
        btpesqt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqtActionPerformed(evt);
            }
        });

        cbbaixado.setText("Baixados");
        cbbaixado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbaixadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbcdias5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdtbi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbcdias6)
                        .addGap(18, 18, 18)
                        .addComponent(tfdtbf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbcdias3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfdtvi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbcdias4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdtvf, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tftotalts, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(cbbaixado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btpesqt)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftotalts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbcdias3)
                        .addComponent(lbcdias4))
                    .addComponent(tfdtvf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdtvi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbcdias5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbcdias6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfdtbf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdtbi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btpesqt)
                    .addComponent(cbbaixado)))
        );

        jtp.addTab("Títulos", jPanel3);

        jMenu7.setText("Arquivo");

        jMenuItem2.setText("Trocar Usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Opções");

        jMenuItem11.setText("Preferências");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar2.add(jMenu8);

        jMenu6.setText("Ajuda/Sobre");

        jMenuItem10.setText("Ajuda/Sobre");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbuseron)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtp)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbuseron))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:

        if (evt.getClickCount() == 2) {
            TreeNode node = (TreeNode) menu.getSelectionPath().getLastPathComponent();
            //testa se é o ultimo nó
            if (node.isLeaf()) {
                if (node.toString().contains("Pessoa")) {
                    if (Util.usuario.isPessoas()) {
                        new CadastroPessoa().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                                + " não possui permissão para acessar este módulo");
                    }

                } else if (node.toString().contains("Itens")) {
                    if (Util.usuario.isProdutos()) {
                        new CadastroItem().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                                + " não possui permissão para acessar este módulo");
                    }

                } else if (node.toString().contains("A Re")) {
                    if (Util.usuario.isAreceber() | Util.usuario.isApagar()) {
                        new Titulos().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                                + " não possui permissão para acessar este módulo");
                    }

                } else if (node.toString().contains("O.S")) {
                    if (Util.usuario.isOs()) {
                        new OS().setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                                + " não possui permissão para acessar este módulo");
                    }

                }
            }

    }//GEN-LAST:event_menuMouseClicked
    }
    private void teste(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teste
        // TODO add your handling code here:
    }//GEN-LAST:event_teste

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

        new Sobre(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Sair ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            System.exit(0);

        } else {

        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente Trocar de Usuário ", "Tem certeza", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);

        } else {

        }


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        btconfig.doClick();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btconfigActionPerformed
        if (Util.usuario.isApagar() && Util.usuario.isAreceber() && Util.usuario.isProdutos() && Util.usuario.isOs()
                && Util.usuario.isUsuarios() && Util.usuario.isPessoas()) {
            new Preferencias(this, rootPaneCheckingEnabled).setVisible(true);
            populaosg();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuário precisa de 'Todas' as permissões para acessar "
                    + "as configurações do sistema");

        }


    }//GEN-LAST:event_btconfigActionPerformed

    private void cbstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbstatusItemStateChanged
        if (cbstatus.getSelectedItem().equals("Andamento")) {
            tfdtfi.setEnabled(false);
            tfdtff.setEnabled(false);
        } else {
            tfdtfi.setEnabled(true);
            tfdtff.setEnabled(true);
            popdata();
        }
    }//GEN-LAST:event_cbstatusItemStateChanged

    private void btpesqospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqospActionPerformed
        populaospesqp();
        if (tbosp.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Nenhuma O.S encontrada no período selecionado");
        }
    }//GEN-LAST:event_btpesqospActionPerformed

    private void cbstatusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbstatusPropertyChange

    }//GEN-LAST:event_cbstatusPropertyChange

    private void tfdtfiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtfiFocusLost
        if (tfdtfi.getDate() == null) {
            popdata();
        }
    }//GEN-LAST:event_tfdtfiFocusLost

    private void tfdtffFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdtffFocusLost
        if (tfdtfi.getDate() == null) {
            popdata();
        }
    }//GEN-LAST:event_tfdtffFocusLost

    private void btpesqtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqtActionPerformed
        populatspesqp();
    }//GEN-LAST:event_btpesqtActionPerformed

    private void cbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbtipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoItemStateChanged

    private void cbtipoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbtipoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoPropertyChange

    private void cbbaixadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbaixadoMouseClicked
        if (cbbaixado.isSelected()) {
            tfdtvi.setEnabled(false);
            tfdtvf.setEnabled(false);
            tfdtbi.setEnabled(true);
            tfdtbf.setEnabled(true);
            popdata2();
            popdata3();

        } else {
            tfdtvi.setEnabled(true);
            tfdtvf.setEnabled(true);
            tfdtbi.setEnabled(false);
            tfdtbf.setEnabled(false);
            tfdtbi.setDate(null);
            tfdtbf.setDate(null);
            calcdata();
        }


    }//GEN-LAST:event_cbbaixadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btconfig;
    private javax.swing.JButton btpesqosp;
    private javax.swing.JButton btpesqt;
    private javax.swing.JCheckBox cbbaixado;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JLabel lbcdias;
    private javax.swing.JLabel lbcdias3;
    private javax.swing.JLabel lbcdias4;
    private javax.swing.JLabel lbcdias5;
    private javax.swing.JLabel lbcdias6;
    private javax.swing.JLabel lbuseron;
    private javax.swing.JTree menu;
    private javax.swing.JTable tbgos;
    private javax.swing.JTable tbosp;
    private javax.swing.JTable tbt;
    private com.toedter.calendar.JDateChooser tfdtbf;
    private com.toedter.calendar.JDateChooser tfdtbi;
    private com.toedter.calendar.JDateChooser tfdtff;
    private com.toedter.calendar.JDateChooser tfdtfi;
    private com.toedter.calendar.JDateChooser tfdtvf;
    private com.toedter.calendar.JDateChooser tfdtvi;
    private javax.swing.JFormattedTextField tftotalos;
    private javax.swing.JFormattedTextField tftotalts;
    // End of variables declaration//GEN-END:variables

    public void populaosg() {

        DefaultTableModel t = (DefaultTableModel) tbgos.getModel();
        t.setNumRows(0);

        tbgos.getColumnModel().getColumn(0).setPreferredWidth(55);
        tbgos.getColumnModel().getColumn(1).setPreferredWidth(157);
        tbgos.getColumnModel().getColumn(2).setPreferredWidth(140);
        tbgos.getColumnModel().getColumn(3).setPreferredWidth(80);

        int tamanho;
        ConfigDAO cd = new ConfigDAO();
        Util.c = cd.listarconfig().get(0);

        OsDAO od = new OsDAO();

        int co = Util.c.getDav();

        int dias = (co);
        lbcdias.setText(dias + " Dias");
        Calendar calend = Calendar.getInstance();
        Date data = new Date();
        calend.setTime(data);
        String dtgi = Util.datatoStringUS(data);
        calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + dias);

        String dtgf = Util.datatoStringUS(calend.getTime());

        List<Os> lista = od.listarosg(dtgi, dtgf);

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Os os = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(os.getCod(), i, 0);
            t.setValueAt(os.getDescricao(), i, 1);
            t.setValueAt(Util.difemdias(Util.DateToDTM(data), Util.StringToDTM(os.getDtg())), i, 2);
            if (os.getDtg() == null) {
                t.setValueAt("", i, 3);
            } else {
                t.setValueAt(Util.convertedataBR(os.getDtg()), i, 3);
            }

        }
    }

    public void populaospesqp() {

        DefaultTableModel t = (DefaultTableModel) tbosp.getModel();
        t.setNumRows(0);
        tbosp.getColumnModel().getColumn(0).setPreferredWidth(55);
        tbosp.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbosp.getColumnModel().getColumn(2).setPreferredWidth(82);
        tbosp.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbosp.getColumnModel().getColumn(4).setPreferredWidth(80);
        tbosp.getColumnModel().getColumn(5).setPreferredWidth(70);

        String status = cbstatus.getSelectedItem().toString();

        String dtfi = Util.datatoStringUS(tfdtfi.getDate());
        String dtff = Util.datatoStringUS(tfdtff.getDate());

        if (cbstatus.getSelectedItem().equals("Andamento")) {
            dtfi = "";
            dtff = "";
        }

        int tamanho;
        List<Os> lista = oscontrol.listaospesq("",
                0, status,
                "1950-01-01",
                "2050-12-30",
                dtfi,
                dtff,
                0);

        if (lista.isEmpty()) {
            popdata();
        }

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Os os = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(os.getCod(), i, 0);
            t.setValueAt(os.getDescricao(), i, 1);
            t.setValueAt(Util.convertedataBR(os.getDta()), i, 2);
            t.setValueAt(os.getClifor(), i, 3);
            t.setValueAt(os.getTotal(), i, 4);
            t.setValueAt(os.getStatus(), i, 5);
        }

        if (!lista.isEmpty()) {
            int ul = tbosp.getRowCount();
            Double ttotal = 0.0;
            for (int l = 0; l < ul; l++) {

                ttotal += Double.parseDouble(tbosp.getValueAt(l, 4).toString());
            }
            DecimalFormat dc = new DecimalFormat("#0.00");

            tftotalos.setText(dc.format(ttotal));

        }

    }

    public void populatspesqp() {

        DefaultTableModel t = (DefaultTableModel) tbt.getModel();
        t.setNumRows(0);
        tbt.getColumnModel().getColumn(0).setPreferredWidth(180);
        tbt.getColumnModel().getColumn(1).setPreferredWidth(80);
        tbt.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbt.getColumnModel().getColumn(3).setPreferredWidth(100);
        int bx;
        if (cbbaixado.isSelected()) {
            bx = 1;
        } else {
            bx = 0;
        }
        String dtvi = Util.datatoStringUS(tfdtvi.getDate());
        String dtvf = Util.datatoStringUS(tfdtvf.getDate());
        String dtbi = Util.datatoStringUS(tfdtbi.getDate());
        String dtbf = Util.datatoStringUS(tfdtbf.getDate());
        
        List<Titulo> listat = tcontrol.listatspesq(
                cbtipo.getSelectedItem().toString(),
                0,
                bx,
                "1950-01-01",
                "2050-12-30",
                dtvi,
                dtvf,
                "",
                dtbi,
                dtbf);

        int tamanho;

        if (listat.isEmpty()) {
            popdata2();
        }

        tamanho = listat.size();
        for (int i = 0; i < tamanho; i++) {
            Titulo ts = listat.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(ts.getClifor(), i, 0);
            t.setValueAt(ts.getQtdparcela(), i, 1);
            t.setValueAt(Util.convertedataBR(ts.getDtv()), i, 2);
            t.setValueAt(ts.getVlrparcela(), i, 3);

        }

        if (!listat.isEmpty()) {
            int ul = tbt.getRowCount();
            Double ttotalt = 0.0;
            for (int l = 0; l < ul; l++) {

                ttotalt += Double.parseDouble(tbt.getValueAt(l, 3).toString());
            }
            DecimalFormat dc = new DecimalFormat("#0.00");

            tftotalts.setText(dc.format(ttotalt));

        }

    }

    private void popdata() {
        tfdtfi.setDate(Util.dataBR("01/01/1950"));
        tfdtff.setDate(Util.dataBR("30/12/2050"));
    }

    private void popdata2() {
        tfdtvi.setDate(Util.dataBR("01/01/1950"));
        tfdtvf.setDate(Util.dataBR("30/12/2050"));
    }

    private void popdata3() {
        tfdtbi.setDate(Util.dataBR("01/01/1950"));
        tfdtbf.setDate(Util.dataBR("30/12/2050"));
    }

    private void calcdata() {
        Calendar calend = Calendar.getInstance();
        Date data = new Date();
        calend.setTime(data);
        calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + 45);
        tfdtvi.setDate(data);
        tfdtvf.setDate(calend.getTime());

    }

}
