/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TituloControl;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import model.Titulo;
import model.Util;
 

/**
 *
 * @author Will
 */
public class TitulosOs extends javax.swing.JDialog {

    SimpleDateFormat dtbr = new SimpleDateFormat("dd/MM/yyyy");
    List<Titulo> titos;
    DecimalFormat dc;
    int flagt;
    TituloControl tc = new TituloControl();

    /**
     * Creates new form TitulosOs
     */
    public TitulosOs(java.awt.Frame parent, boolean modal, Titulo t, int flag) {
        super(parent, modal);
        initComponents();
        tfentrada.setText("0");
        titos = new ArrayList<>();
        dc = new DecimalFormat("#0.00");
        formtos();
        flagt = flag;

        if (flag == 1) {
            if (t.getId() != -1) {
                poptos(t);
            }

        }
        if (flag == 2) {
            desativatos();
            popts2(t);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtos = new javax.swing.JTable();
        tfdocos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfparcela = new javax.swing.JSpinner();
        tfcodp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfpessoa = new javax.swing.JTextField();
        cbformpag = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        tfvlrparcela = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfvlrtotal = new javax.swing.JTextField();
        tfemissao = new com.toedter.calendar.JDateChooser();
        tfdescobs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfvencimento = new javax.swing.JSpinner();
        btgerart = new javax.swing.JButton();
        tfentrada = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Título O.S");
        setResizable(false);

        btok.setText("Ok");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        tbtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc / O.S", "Tipo", "Parcela", "Cod Cli/For", "Cliente/For", "Form. Pag.", "Vlr Parcela R$", "Vlr Total R$", "Emissão", "Vencimento", "Desc / OBS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tbtos);
        tbtos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbtos.getColumnModel().getColumnCount() > 0) {
            tbtos.getColumnModel().getColumn(0).setResizable(false);
            tbtos.getColumnModel().getColumn(1).setResizable(false);
            tbtos.getColumnModel().getColumn(2).setResizable(false);
            tbtos.getColumnModel().getColumn(3).setResizable(false);
            tbtos.getColumnModel().getColumn(4).setResizable(false);
            tbtos.getColumnModel().getColumn(5).setResizable(false);
            tbtos.getColumnModel().getColumn(6).setResizable(false);
            tbtos.getColumnModel().getColumn(7).setResizable(false);
            tbtos.getColumnModel().getColumn(8).setResizable(false);
            tbtos.getColumnModel().getColumn(9).setResizable(false);
            tbtos.getColumnModel().getColumn(10).setResizable(false);
        }

        tfdocos.setEditable(false);

        jLabel1.setText("Doc / O.S");

        jLabel2.setText("Parcelas");

        tfparcela.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));
        tfparcela.setToolTipText("");
        tfparcela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfparcela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfparcelaStateChanged(evt);
            }
        });
        tfparcela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfparcelaMouseClicked(evt);
            }
        });
        tfparcela.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfparcelaPropertyChange(evt);
            }
        });

        tfcodp.setEditable(false);

        jLabel3.setText("Cod");

        jLabel4.setText("Cliente / For");

        tfpessoa.setEditable(false);

        cbformpag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Duplicata (Loja)", "Dinheiro", "Cartão", "Chegue", " " }));

        jLabel5.setText("Forma Pagamento");

        jLabel6.setText("Tipo ");

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Receber" }));

        tfvlrparcela.setEditable(false);
        tfvlrparcela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Valor Parcela  R$");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Valor Total     R$");

        tfvlrtotal.setEditable(false);
        tfvlrtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tfemissao.setEnabled(false);

        jLabel9.setText("Descrição/OBS");

        jLabel10.setText("Emissão");

        jLabel11.setText("Intervalo Venc");

        tfvencimento.setModel(new javax.swing.SpinnerNumberModel(30, 1, 99, 1));
        tfvencimento.setToolTipText("");
        tfvencimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btgerart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btgerart.setText("Gerar Títulos");
        btgerart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgerartActionPerformed(evt);
            }
        });

        tfentrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfentradaFocusLost(evt);
            }
        });

        jLabel12.setText("Entrada      R$");

        jLabel13.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btok)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfdocos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(tfcodp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btgerart)
                                        .addComponent(tfdescobs, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfemissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbformpag, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfvlrtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfvlrparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdocos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfcodp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tfpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbformpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdescobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(tfemissao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btgerart))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfvlrparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfvlrtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btok)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        if (flagt == 1) {
            if (tbtos.getRowCount() != 0) {
                int ul = tbtos.getRowCount();
                for (int l = 0; l < ul; l++) {
                    Titulo t = new Titulo();
                    t.setDoc(Integer.parseInt(tbtos.getValueAt(l, 0).toString()));
                    t.setTipo(tbtos.getValueAt(l, 1).toString());
                    t.setQtdparcela(tbtos.getValueAt(l, 2).toString());
                    t.setIdclifor(Integer.parseInt(tbtos.getValueAt(l, 3).toString()));
                    t.setClifor(tbtos.getValueAt(l, 4).toString());
                    t.setFormpag(tbtos.getValueAt(l, 5).toString());
                    t.setVlrparcela(Double.parseDouble(tbtos.getValueAt(l, 6).toString()));
                    t.setVlrtotal(Double.parseDouble(tbtos.getValueAt(l, 7).toString()));
                    t.setDte(Util.convertedataUS(tbtos.getValueAt(l, 8).toString()));
                    t.setDtv(Util.convertedataUS(tbtos.getValueAt(l, 9).toString()));
                    t.setDescos(tbtos.getValueAt(l, 10).toString());
                    if (tbtos.getValueAt(l, 5).toString().equals("Dinheiro")) {
                        t.setBaixado(true);
                        t.setVlrbaixa(Double.parseDouble(tbtos.getValueAt(l, 6).toString()));
                        t.setDtb(Util.convertedataUS(tbtos.getValueAt(l, 8).toString()));
                    } else {
                        t.setBaixado(false);
                        t.setVlrbaixa(0.0);
                        t.setDtb("");
                    }
                    t.setVlrpago(0.0);
                    
                    titos.add(t);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(tfvencimento, "Gerar pelo menos uma parcela para continuar");
            }
        }
        if (flagt == 2) {
            this.dispose();
        }

    }//GEN-LAST:event_btokActionPerformed

    private void btgerartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgerartActionPerformed
        DefaultTableModel t = (DefaultTableModel) tbtos.getModel();
        t.setNumRows(0);

        String docos = tfdocos.getText();
        String idclifor = tfcodp.getText();
        String clifor = tfpessoa.getText();
        int parc = Integer.parseInt(tfparcela.getValue().toString());
        String tipo = cbtipo.getSelectedItem().toString();
        String formpag = cbformpag.getSelectedItem().toString();
        String descos = tfdescobs.getText();
        String dte = Util.datatoStringBR(tfemissao.getDate());
        int pvenc = Integer.parseInt(tfvencimento.getValue().toString());
        Double vlrparc = Double.parseDouble(tfvlrparcela.getText().replace(",", "."));
        Double vlrtot = Double.parseDouble(tfvlrtotal.getText().replace(",", "."));
        Double vlrentrada = Double.parseDouble(tfentrada.getText().replace(",", "."));
        int l2 = 1;

        if (vlrentrada != 0) {
            if (Objects.equals(vlrentrada, vlrtot)) {
                parc = 0;
                tfparcela.setValue(1);
            }

            parc += 1;
            t.addRow(new Object[]{docos, tipo, 1 + "/" + parc, idclifor, clifor, "Dinheiro", vlrentrada, vlrtot, dte,
                dte, "Ref. entrada - " + descos});
            l2 = 2;

        }
        if (vlrentrada < vlrtot) {
            for (int l = l2; l <= parc; l++) {
                try {
                    Calendar calend = Calendar.getInstance();
                    calend.setTime(tfemissao.getDate());
                    if (vlrentrada != 0) {
                        int l3 = l - 1;
                        calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + pvenc * l3);
                    } else {
                        calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + pvenc * l);
                    }

                    t.addRow(new Object[]{docos, tipo, l + "/" + parc, idclifor, clifor, formpag, vlrparc, vlrtot, dte,
                        (dtbr.format(calend.getTime())), descos});

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(tfvencimento, "Erro ao Gerar Parcelas");
                    printStackTrace(ex);
                }

            }
        }
    }//GEN-LAST:event_btgerartActionPerformed

    private void tfparcelaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfparcelaPropertyChange


    }//GEN-LAST:event_tfparcelaPropertyChange

    private void tfparcelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfparcelaMouseClicked

    }//GEN-LAST:event_tfparcelaMouseClicked

    private void tfparcelaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfparcelaStateChanged
        calcvlr();
    }//GEN-LAST:event_tfparcelaStateChanged

    private void tfentradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfentradaFocusLost
        if (tfentrada.getText().isEmpty()) {
            tfentrada.setText("0");
        }
        Double vlrtot = Double.parseDouble(tfvlrtotal.getText().replace(",", "."));
        Double vlrentrada = Double.parseDouble(tfentrada.getText().replace(",", "."));

        if (vlrentrada > vlrtot) {
            tfentrada.setText(String.valueOf(dc.format(vlrtot)));
        }

        calcvlr();
    }//GEN-LAST:event_tfentradaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitulosOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitulosOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitulosOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitulosOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TitulosOs dialog = new TitulosOs(new javax.swing.JFrame(), true, null, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgerart;
    private javax.swing.JButton btok;
    private javax.swing.JComboBox<String> cbformpag;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtos;
    private javax.swing.JTextField tfcodp;
    private javax.swing.JTextField tfdescobs;
    private javax.swing.JTextField tfdocos;
    private com.toedter.calendar.JDateChooser tfemissao;
    private javax.swing.JTextField tfentrada;
    private javax.swing.JSpinner tfparcela;
    private javax.swing.JTextField tfpessoa;
    private javax.swing.JSpinner tfvencimento;
    private javax.swing.JTextField tfvlrparcela;
    private javax.swing.JTextField tfvlrtotal;
    // End of variables declaration//GEN-END:variables
private void formtos() {
        tbtos.getColumnModel().getColumn(0).setPreferredWidth(70);
        tbtos.getColumnModel().getColumn(1).setPreferredWidth(65);
        tbtos.getColumnModel().getColumn(2).setPreferredWidth(70);
        tbtos.getColumnModel().getColumn(3).setPreferredWidth(60);
        tbtos.getColumnModel().getColumn(4).setPreferredWidth(160);
        tbtos.getColumnModel().getColumn(5).setPreferredWidth(120);
        tbtos.getColumnModel().getColumn(6).setPreferredWidth(80);
        tbtos.getColumnModel().getColumn(7).setPreferredWidth(80);
        tbtos.getColumnModel().getColumn(8).setPreferredWidth(80);
        tbtos.getColumnModel().getColumn(9).setPreferredWidth(80);
        tbtos.getColumnModel().getColumn(10).setPreferredWidth(150);

    }

    public void poptos(Titulo t) {
//        try {
        tfdocos.setText(String.valueOf(t.getDoc()));
        tfcodp.setText(String.valueOf(t.getIdclifor()));
        tfpessoa.setText(String.valueOf(t.getClifor()));
        tfemissao.setDate(Util.dataBR(t.getDte()));
        tfdescobs.setText(t.getDescos());
        tfvlrtotal.setText(String.valueOf(dc.format(t.getVlrtotal())));
        calcvlr();
//        } catch (Exception ex) {
//            printStackTrace(ex);
//        }

        //JOptionPane.showMessageDialog(tfvencimento, t.getDte());
    }

    public void desativatos() {
        btgerart.setEnabled(false);
        tfparcela.setEnabled(false);
        tfdescobs.setEnabled(false);
        tfvencimento.setEnabled(false);
        tfentrada.setEnabled(false);
        cbformpag.setEnabled(false);
        cbtipo.setEnabled(false);

    }

    private void calcvlr() {
        Double vlrtot = Double.parseDouble(tfvlrtotal.getText().replace(",", "."));
        int parc = Integer.parseInt(tfparcela.getValue().toString());
        Double entrada = Double.parseDouble(tfentrada.getText().replace(",", "."));
        Double vfinal = vlrtot - entrada;
        Double calc = vfinal / parc;
        tfvlrparcela.setText(String.valueOf(dc.format(calc)));
    }
    
    private void popts2(Titulo t){
        DefaultTableModel tb = (DefaultTableModel) tbtos.getModel();
        tb.setNumRows(0);

        int tamanho;
        List<Titulo> lista = tc.listartos(t.getIdclifor(),t.getDoc());

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++){
            Titulo ti = lista.get(i);
            tb.addRow(new Object[]{ti.getDoc(), ti.getTipo(),ti.getQtdparcela(), ti.getIdclifor(), 
                ti.getClifor(),ti.getFormpag(), ti.getVlrparcela(),ti.getVlrtotal(), Util.convertedataBR(ti.getDte()),
                Util.convertedataBR(ti.getDtv()),ti.getDescos()});
                
            
        }
        
        
        
        
    }
}
