/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TituloControl;

import dao.TituloDAO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import model.Conexao;
import model.Os;
import model.Titulo;
import model.Util;

/**
 *
 * @author Igor
 */
public class Titulos extends javax.swing.JFrame {

    //model.Titulo ti = new model.Titulo();
    TituloControl tcontrol;
    Buscapessoa buscap;
    int flag = 0;
    List<Titulo> exititulo;
    boolean ts;
    boolean tb;
    int ls;
    Date data = new Date();
    DecimalFormat dc;

    /**
     * Creates new form Titulo
     */
    public Titulos() {
        initComponents();
        desativarcampos();
        tcontrol = new TituloControl();
        formtitulo();
        tbts.setAutoCreateRowSorter(true);
        exititulo = new ArrayList<>();
        btGerartitulo.setEnabled(false);
        btbaixar.setEnabled(false);
        ls = 0;
        dc = new DecimalFormat("#0.00");
        dataspesq();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncancelar = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnnovo = new javax.swing.JButton();
        btexcluir = new javax.swing.JButton();
        pnlselecao = new javax.swing.JPanel();
        rbReceber = new javax.swing.JRadioButton();
        rbApagar = new javax.swing.JRadioButton();
        lbemissao = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfdtei = new com.toedter.calendar.JDateChooser();
        tfdtvi = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdtef = new com.toedter.calendar.JDateChooser();
        tfdtvf = new com.toedter.calendar.JDateChooser();
        cbtipo = new javax.swing.JComboBox<>();
        cbbaixado = new javax.swing.JCheckBox();
        btbuscats = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        blcliente = new javax.swing.JLabel();
        tfcodp = new javax.swing.JTextField();
        tfcliente = new javax.swing.JTextField();
        btpesq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfidt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfdoc = new javax.swing.JTextField();
        nometitulo = new javax.swing.JLabel();
        lbvalortotal = new javax.swing.JLabel();
        tftotal = new javax.swing.JTextField();
        lbformapgt = new javax.swing.JLabel();
        cbxformadepgt = new javax.swing.JComboBox<>();
        lbparcela1 = new javax.swing.JLabel();
        lbdatanacimento = new javax.swing.JLabel();
        tftotts = new javax.swing.JTextField();
        txtdatabaixa = new com.toedter.calendar.JDateChooser();
        lbdatabaixa = new javax.swing.JLabel();
        lbsaldo = new javax.swing.JLabel();
        tfdescobs = new javax.swing.JTextField();
        lbparcela = new javax.swing.JLabel();
        tfvlrparcela = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btbaixar = new javax.swing.JButton();
        btGerartitulo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbts = new javax.swing.JTable();
        tfdescobspesq = new javax.swing.JTextField();
        lbemissao1 = new javax.swing.JLabel();
        lbemissao2 = new javax.swing.JLabel();
        blcliente1 = new javax.swing.JLabel();
        tfqtdp = new javax.swing.JSpinner();
        tfvenc = new javax.swing.JSpinner();
        tfdte = new com.toedter.calendar.JDateChooser();
        lbvalortotal1 = new javax.swing.JLabel();
        lbvalortotal2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas Pagar/Receber");
        setResizable(false);

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btncancelar.setText("Cancelar ");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield-1.png"))); // NOI18N
        btnsalvar.setText("Salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/user.png"))); // NOI18N
        btnnovo.setText("Novo");
        btnnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovoActionPerformed(evt);
            }
        });

        btexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield.png"))); // NOI18N
        btexcluir.setText("Excluir");
        btexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexcluirActionPerformed(evt);
            }
        });

        pnlselecao.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta*"));

        rbReceber.setText("A Receber");
        rbReceber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbReceberItemStateChanged(evt);
            }
        });
        rbReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReceberActionPerformed(evt);
            }
        });

        rbApagar.setText("A Pagar");
        rbApagar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbApagarItemStateChanged(evt);
            }
        });
        rbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlselecaoLayout = new javax.swing.GroupLayout(pnlselecao);
        pnlselecao.setLayout(pnlselecaoLayout);
        pnlselecaoLayout.setHorizontalGroup(
            pnlselecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlselecaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbReceber)
                .addGap(6, 6, 6)
                .addComponent(rbApagar))
        );
        pnlselecaoLayout.setVerticalGroup(
            pnlselecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlselecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbReceber))
        );

        lbemissao.setText("Emissão");

        jLabel9.setText("Vencimento");

        jLabel7.setText("Inicio");

        jLabel3.setText("Inicio");

        jLabel4.setText("Final");

        jLabel5.setText("Final");

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Receber", "A Pagar" }));

        cbbaixado.setText("Baixados");
        cbbaixado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbaixadoItemStateChanged(evt);
            }
        });
        cbbaixado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbaixadoActionPerformed(evt);
            }
        });

        btbuscats.setText("Pesquisar Titulo");
        btbuscats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscatsActionPerformed(evt);
            }
        });

        blcliente.setText("Código*");

        tfcodp.setEnabled(false);
        tfcodp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodpActionPerformed(evt);
            }
        });

        tfcliente.setEnabled(false);
        tfcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfclienteActionPerformed(evt);
            }
        });

        btpesq.setText("Pesquisar");
        btpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpesqActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        tfidt.setEnabled(false);
        tfidt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidtActionPerformed(evt);
            }
        });

        jLabel2.setText("Documento*");

        tfdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdocActionPerformed(evt);
            }
        });

        nometitulo.setText("Desc \\ Obs");

        lbvalortotal.setText("Valor Total*");

        tftotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tftotalFocusLost(evt);
            }
        });
        tftotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftotalActionPerformed(evt);
            }
        });

        lbformapgt.setText("Formas de Pagamento*");

        cbxformadepgt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Duplicata (Loja)", "Dinheiro", "Cheque", "Cartão", " " }));
        cbxformadepgt.setToolTipText("");

        lbparcela1.setText("Qtd de Parcela*");

        lbdatanacimento.setText("Intervalo Venc.*");

        tftotts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tftotts.setEnabled(false);
        tftotts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftottsActionPerformed(evt);
            }
        });

        txtdatabaixa.setEnabled(false);

        lbdatabaixa.setText("Data Baixa");

        lbsaldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbsaldo.setText("Total Títulos   R$");

        tfdescobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdescobsActionPerformed(evt);
            }
        });

        lbparcela.setText("Valor Parcela");

        tfvlrparcela.setEnabled(false);
        tfvlrparcela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfvlrparcelaFocusLost(evt);
            }
        });

        jLabel8.setText("Data Emissao*");

        btbaixar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btbaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon16/shield-1.png"))); // NOI18N
        btbaixar.setText("Baixar");
        btbaixar.setEnabled(false);
        btbaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbaixarActionPerformed(evt);
            }
        });

        btGerartitulo.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        btGerartitulo.setText("Gerar título");
        btGerartitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerartituloActionPerformed(evt);
            }
        });

        tbts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Documento", "Tipo", "Id.Cliente", "NomeCliente", "Desc/Obs", "Parcela", "V.Parcela", "F.Pagamento", "V.Total", "Vencimento", "DataBaixa", "DataEmissao", "Valorbaixa", "Baixado?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbts.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbts.getTableHeader().setReorderingAllowed(false);
        tbts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbts);
        tbts.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbts.getColumnModel().getColumnCount() > 0) {
            tbts.getColumnModel().getColumn(0).setResizable(false);
            tbts.getColumnModel().getColumn(1).setResizable(false);
            tbts.getColumnModel().getColumn(2).setResizable(false);
            tbts.getColumnModel().getColumn(3).setResizable(false);
            tbts.getColumnModel().getColumn(4).setResizable(false);
            tbts.getColumnModel().getColumn(5).setResizable(false);
            tbts.getColumnModel().getColumn(6).setResizable(false);
            tbts.getColumnModel().getColumn(7).setResizable(false);
            tbts.getColumnModel().getColumn(8).setResizable(false);
            tbts.getColumnModel().getColumn(9).setResizable(false);
            tbts.getColumnModel().getColumn(10).setResizable(false);
            tbts.getColumnModel().getColumn(11).setResizable(false);
            tbts.getColumnModel().getColumn(12).setResizable(false);
            tbts.getColumnModel().getColumn(13).setResizable(false);
            tbts.getColumnModel().getColumn(14).setResizable(false);
        }

        tfdescobspesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdescobspesqActionPerformed(evt);
            }
        });
        tfdescobspesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdescobspesqKeyPressed(evt);
            }
        });

        lbemissao1.setText("Descrição");

        lbemissao2.setText("Tipo");

        blcliente1.setText("Cliente*");

        tfqtdp.setModel(new javax.swing.SpinnerNumberModel(2, 1, 99, 1));
        tfqtdp.setEnabled(false);
        tfqtdp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tfqtdpStateChanged(evt);
            }
        });

        tfvenc.setModel(new javax.swing.SpinnerNumberModel(30, 1, 99, 1));
        tfvenc.setEnabled(false);

        tfdte.setEnabled(false);

        lbvalortotal1.setText("R$");

        lbvalortotal2.setText("R$");

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Campos obrigatórios para gerar parcelas marcados com *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbparcela1)
                                                .addComponent(lbdatabaixa))
                                            .addComponent(blcliente, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfcodp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfqtdp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbdatanacimento)
                                                    .addComponent(blcliente1)
                                                    .addComponent(nometitulo)))
                                            .addComponent(txtdatabaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(tfvenc, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lbparcela)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(lbvalortotal2)
                                                        .addGap(1, 1, 1)
                                                        .addComponent(tfvlrparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tfdte, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(tfdescobs, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(btpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfidt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(21, 21, 21))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbformapgt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxformadepgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbvalortotal)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbvalortotal1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(btGerartitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlselecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnnovo)
                            .addGap(20, 20, 20)
                            .addComponent(btnsalvar)
                            .addGap(18, 18, 18)
                            .addComponent(btexcluir)
                            .addGap(26, 26, 26)
                            .addComponent(btbaixar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbemissao2)
                                    .addGap(30, 30, 30)
                                    .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbbaixado))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbemissao1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfdescobspesq, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(btbuscats)))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbemissao)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfdtei, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(tfdtef, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfdtvi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(tfdtvf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(542, 542, 542)
                            .addComponent(btncancelar)
                            .addGap(26, 26, 26)
                            .addComponent(lbsaldo)
                            .addGap(18, 18, 18)
                            .addComponent(tftotts))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lbemissao1))
                                    .addComponent(btbuscats)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(tfdtei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(tfdtef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tfdescobspesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbemissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbemissao2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbaixado)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfdtvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfdtvf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlselecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpesq)
                    .addComponent(blcliente1)
                    .addComponent(tfcodp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(blcliente))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbformapgt)
                            .addComponent(cbxformadepgt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nometitulo)
                                    .addComponent(tfdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbparcela1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfqtdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbdatanacimento)
                                    .addComponent(tfvenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbparcela, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfvlrparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbvalortotal2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdatabaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbdatabaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfdte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfdescobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btGerartitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbvalortotal)
                                .addComponent(tftotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbvalortotal1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tftotts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnovo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsalvar)
                                .addComponent(btexcluir))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btbaixar)
                                .addComponent(btncancelar)))))
                .addGap(18, 18, 18))
        );

        setSize(new java.awt.Dimension(914, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void rbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbApagarActionPerformed
        if (Util.usuario.isApagar()) {
            rbReceber.setEnabled(false);
            ativarcampos();
            btGerartitulo.setEnabled(true);
            btbaixar.setEnabled(false);
            tftotts.setEnabled(false);
        } else {
            rbApagar.setSelected(false);
            JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                    + " não possui permissão!");
        }


    }//GEN-LAST:event_rbApagarActionPerformed

    public void limparcampos() {

        tfcodp.setText("0");
        tfcliente.setText("");
        tfdoc.setText("");
        tftotal.setText("");
        tfcliente.setText("");
        tfvlrparcela.setText("");
        tftotts.setText("");
        tfidt.setText("");
        tfdescobs.setText("");
        txtdatabaixa.setDate(null);
        tfdte.setDate(null);
        rbReceber.setSelected(false);
        rbApagar.setSelected(false);

        DefaultTableModel t = (DefaultTableModel) tbts.getModel();
        t.setRowCount(0);
    }

    public void desativarcampos() {
        rbReceber.setEnabled(false);
        rbApagar.setEnabled(false);
        tfcodp.setEnabled(false);
        tftotal.setEnabled(false);
        tfcliente.setEnabled(false);
        txtdatabaixa.setEnabled(false);
        tftotts.setEnabled(false);
        cbxformadepgt.setEnabled(false);
        cbxformadepgt.setEnabled(false);
        btpesq.setEnabled(false);
        tfidt.setEnabled(false);
        tfvlrparcela.setEnabled(false);
        tfdescobs.setEnabled(false);
        btnsalvar.setEnabled(false);
        btexcluir.setEnabled(false);
        tfdoc.setEnabled(false);
        btGerartitulo.setEnabled(false);
        tfvenc.setEnabled(false);
        tfqtdp.setEnabled(false);
        tfdte.setEnabled(false);

    }

    public void ativarcampos() {
        tfqtdp.setEnabled(true);
        tfvenc.setEnabled(true);
        tftotal.setEnabled(true);
        cbxformadepgt.setEnabled(true);
        btpesq.setEnabled(true);
        tfdescobs.setEnabled(true);
        btnsalvar.setEnabled(true);
        tfdoc.setEnabled(true);
        tfdte.setEnabled(true);

    }

    private void rbApagarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbApagarItemStateChanged

    }//GEN-LAST:event_rbApagarItemStateChanged

    private void rbReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReceberActionPerformed
        if (Util.usuario.isAreceber()) {
            rbApagar.setEnabled(false);
            ativarcampos();
            btGerartitulo.setEnabled(true);
            btbaixar.setEnabled(false);
            tftotts.setEnabled(false);
        } else {
            rbReceber.setSelected(false);
            JOptionPane.showMessageDialog(rootPane, "Usuário " + Util.usuario.getNome()
                    + " não possui permissão!");
        }


    }//GEN-LAST:event_rbReceberActionPerformed

    private void rbReceberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbReceberItemStateChanged

    }//GEN-LAST:event_rbReceberItemStateChanged

    private void tftottsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftottsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftottsActionPerformed

    private void tfclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfclienteActionPerformed

    private void tftotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftotalActionPerformed

    private void tfcodpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodpActionPerformed

    private void btnnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovoActionPerformed

        limparcampos();
        flag = 1;
        rbReceber.setEnabled(true);
        rbApagar.setEnabled(true);
        btnnovo.setEnabled(false);
        tfdte.setDate(data);

    }//GEN-LAST:event_btnnovoActionPerformed


    private void btpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpesqActionPerformed

        buscap = new Buscapessoa(this, true, "abrir", 0);
        buscap.setVisible(true);

        tfcodp.setText(String.valueOf(buscap.p.getCodpessoa()));
        tfcliente.setText(buscap.p.getNome());

    }//GEN-LAST:event_btpesqActionPerformed

    private void tfidtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidtActionPerformed

    }//GEN-LAST:event_tfidtActionPerformed

    @SuppressWarnings("empty-statement")


    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        if (tbts.getRowCount() > 0) {
            if (flag == 1) {

                Titulo t = new Titulo();

                DefaultTableModel u = (DefaultTableModel) tbts.getModel();
                int ul = u.getRowCount();
                for (int l = 0; l < ul; l++) {

                    t.setDoc(Integer.parseInt(u.getValueAt(l, 1).toString()));
                    t.setTipo(u.getValueAt(l, 2).toString());
                    t.setIdclifor(Integer.parseInt(u.getValueAt(l, 3).toString()));
                    t.setClifor(u.getValueAt(l, 4).toString());
                    t.setDescos(u.getValueAt(l, 5).toString());
                    t.setQtdparcela(u.getValueAt(l, 6).toString());
                    t.setVlrparcela(Double.parseDouble(u.getValueAt(l, 7).toString()));
                    t.setFormpag(u.getValueAt(l, 8).toString());
                    t.setVlrtotal(Double.parseDouble(u.getValueAt(l, 9).toString()));
                    t.setDtv(Util.convertedataUS(u.getValueAt(l, 10).toString()));
                    t.setDtb(Util.convertedataUS(u.getValueAt(l, 11).toString()));
                    t.setDte(Util.convertedataUS(u.getValueAt(l, 12).toString()));
                    t.setVlrbaixa(Double.parseDouble(u.getValueAt(l, 13).toString()));
                    t.setBaixado(false);
                    t.setVlrpago(0.0);

                    ts = tcontrol.salvar(t);

                }
                if (ts) {
                    limparcampos();
                    desativarcampos();
                    JOptionPane.showMessageDialog(rootPane, "Dados Gravados com sucesso");
                    btnnovo.setEnabled(true);

                } else {

                    JOptionPane.showMessageDialog(rootPane, "Falha ao Gravar");

                }

            }

            if (flag == 2) {

                Titulo t = new Titulo();

                DefaultTableModel u = (DefaultTableModel) tbts.getModel();
                int ul = u.getRowCount();
                for (int l = 0; l < ul; l++) {

                    if (u.getValueAt(l, 14).toString().equals("Baixado")) {
                        t.setBaixado(true);
                        t.setDtb(Util.convertedataUS(u.getValueAt(l, 11).toString()));
                        t.setVlrbaixa(Double.parseDouble(u.getValueAt(l, 13).toString()));
                        t.setId(Integer.parseInt(u.getValueAt(l, 0).toString()));
                        tb = tcontrol.alterar(t);
                    }

                }

                if (tb) {
                    JOptionPane.showMessageDialog(rootPane, "Dados Baixados com sucesso");
                    limparcampos();
                    desativarcampos();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Falha ao Baixar");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Gerar pelo menos uma parcela");
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void tfdescobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdescobsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdescobsActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Deseja cancelar", "", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {

            limparcampos();
            desativarcampos();
            btnnovo.setEnabled(true);
            rbReceber.setSelected(false);
            rbApagar.setSelected(false);
        }
    }//GEN-LAST:event_btncancelarActionPerformed

    private void tfdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdocActionPerformed

    private void btGerartituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerartituloActionPerformed
        if (tfcliente.getText().isEmpty() | tfdoc.getText().isEmpty() | tftotal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Preencha os campos obrigatórios para gerar os titulos");
        } else {

            DefaultTableModel t = (DefaultTableModel) tbts.getModel();
            t.setNumRows(0);
            String tipo;
            if (rbReceber.isSelected()) {
                tipo = "A Receber";

            } else {

                tipo = "A Pagar";

            }

            int doc = Integer.parseInt(tfdoc.getText());
            double vlrt = Double.parseDouble(tftotal.getText().replace(",", "."));
            String ncliente = (tfcliente.getText());
            int idcli = Integer.parseInt(tfcodp.getText());
            String formp = (cbxformadepgt.getSelectedItem().toString());
            String desc = (tfdescobs.getText());
            int qtdp = Integer.parseInt(tfqtdp.getValue().toString());
            double vlparc = Double.parseDouble(tfvlrparcela.getText().replace(",", "."));
            int pvenc = Integer.parseInt(tfvenc.getValue().toString());
            Date dte = tfdte.getDate();

            for (int l = 1; l <= qtdp; l++) {

                SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
                Calendar calend = Calendar.getInstance();
                calend.setTime(dte);
                calend.set(Calendar.DAY_OF_MONTH, calend.get(Calendar.DAY_OF_MONTH) + pvenc * l);

                t.addRow(new Object[]{"", doc, tipo, idcli, ncliente, desc, +l + "/" + qtdp, vlparc,
                    formp, vlrt, f.format(calend.getTime()), "", f.format(dte), "0", ""});
                calctot();
            }

        }
    }//GEN-LAST:event_btGerartituloActionPerformed

    private void tfvlrparcelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfvlrparcelaFocusLost


    }//GEN-LAST:event_tfvlrparcelaFocusLost
    private void calctot() {

        try {
            Double vtot2 = 0.0;
            for (int i = 0; i < tbts.getRowCount(); i++) {
                vtot2 += Double.parseDouble(tbts.getValueAt(i, 7).toString());
                tftotts.setText(dc.format(vtot2));
            }
        } catch (Exception ex) {
            printStackTrace(ex);
        }

    }


    private void tbtsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtsMouseClicked
        ls = tbts.getSelectedRow();
        if (!tbts.getValueAt(ls, 14).equals("Baixado") && flag == 2) {
            if (evt.getClickCount() == 2) {
                double valortotal = 0;
                double valorbaixa = 0;

                int lt = tbts.getRowCount();

                JOptionPane.showMessageDialog(null, "Titulo Cod: " + tbts.getValueAt(ls, 0) + " Selecionado");

                btbaixar.setEnabled(true);
                btexcluir.setEnabled(true);
                btnnovo.setEnabled(false);

                tfidt.setText(tbts.getModel().getValueAt(ls, 0).toString());
                tfdoc.setText(tbts.getModel().getValueAt(ls, 1).toString());
                if (tbts.getModel().getValueAt(ls, 2).toString().equals("A Receber")) {
                    rbReceber.setSelected(true);
                    rbApagar.setSelected(false);
                } else {
                    rbApagar.setSelected(true);
                    rbReceber.setSelected(false);
                }
                tfcodp.setText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 3).toString());
                tfcliente.setText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 4).toString());
                tfdescobs.setText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 5).toString());
                tfvlrparcela.setText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 7).toString());
                cbxformadepgt.setToolTipText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 8).toString());
                tftotal.setText(tbts.getModel().getValueAt(tbts.getSelectedRow(), 9).toString());
                txtdatabaixa.setDate(Util.dataBR(tbts.getModel().getValueAt(tbts.getSelectedRow(), 12).toString()));
    }//GEN-LAST:event_tbtsMouseClicked
        }
    }
    private void btbuscatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscatsActionPerformed
        limparcampos();
        desativarcampos();
        buscap = new Buscapessoa(this, true, "", 0);
        buscap.setVisible(true);
        tfcodp.setText(String.valueOf(buscap.p.getCodpessoa()));
        tfcliente.setText(buscap.p.getNome());
        btbaixar.setEnabled(false);
        cbxformadepgt.setEnabled(true);
        btGerartitulo.setEnabled(false);
        populatitulo();
        flag = 2;
        calctot();
    }//GEN-LAST:event_btbuscatsActionPerformed

    private void btexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexcluirActionPerformed

        int Documento = 1;
        Object obj = tbts.getValueAt(tbts.getSelectedRow(),
                Documento);

        int reply = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Titulo " + obj + "?", "Tem certeza ?", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {

            if (tbts.getSelectedRow() >= 0) {
                DefaultTableModel t = (DefaultTableModel) tbts.getModel();
                boolean tr = tcontrol.removertitulo(Integer.parseInt(t.getValueAt(tbts.getSelectedRow(), 1).toString()),
                        Integer.parseInt(t.getValueAt(tbts.getSelectedRow(), 3).toString()));
                limparcampos();
                desativarcampos();
                t.setNumRows(0);
                btnnovo.setEnabled(true);
                if (tr) {
                    JOptionPane.showMessageDialog(rootPane, "Título removido com sucesso");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione um título para excluir");
            }
        }

    }//GEN-LAST:event_btexcluirActionPerformed

    private void btbaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbaixarActionPerformed

        txtdatabaixa.setDate(data);
        SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy");
        tbts.setValueAt(tfvlrparcela.getText(), ls, 13);
        tbts.setValueAt(f.format(txtdatabaixa.getDate()), ls, 11);
        tbts.setValueAt("Baixado", ls, 14);
        btnsalvar.setEnabled(true);
    }//GEN-LAST:event_btbaixarActionPerformed

    private void tfdescobspesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdescobspesqActionPerformed

    }//GEN-LAST:event_tfdescobspesqActionPerformed

    private void tfqtdpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tfqtdpStateChanged
        calcula();
    }//GEN-LAST:event_tfqtdpStateChanged

    private void tftotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftotalFocusLost
        calcula();
    }//GEN-LAST:event_tftotalFocusLost

    private void cbbaixadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbaixadoItemStateChanged

    }//GEN-LAST:event_cbbaixadoItemStateChanged

    private void cbbaixadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbaixadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbaixadoActionPerformed

    private void tfdescobspesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdescobspesqKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btbuscats.doClick();
        }
    }//GEN-LAST:event_tfdescobspesqKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Titulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Titulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Titulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Titulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Titulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blcliente;
    private javax.swing.JLabel blcliente1;
    private javax.swing.JButton btGerartitulo;
    private javax.swing.JButton btbaixar;
    private javax.swing.JButton btbuscats;
    private javax.swing.JButton btexcluir;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnnovo;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btpesq;
    private javax.swing.JCheckBox cbbaixado;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JComboBox<String> cbxformadepgt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbdatabaixa;
    private javax.swing.JLabel lbdatanacimento;
    private javax.swing.JLabel lbemissao;
    private javax.swing.JLabel lbemissao1;
    private javax.swing.JLabel lbemissao2;
    private javax.swing.JLabel lbformapgt;
    private javax.swing.JLabel lbparcela;
    private javax.swing.JLabel lbparcela1;
    private javax.swing.JLabel lbsaldo;
    private javax.swing.JLabel lbvalortotal;
    private javax.swing.JLabel lbvalortotal1;
    private javax.swing.JLabel lbvalortotal2;
    private javax.swing.JLabel nometitulo;
    private javax.swing.JPanel pnlselecao;
    private javax.swing.JRadioButton rbApagar;
    private javax.swing.JRadioButton rbReceber;
    private javax.swing.JTable tbts;
    private javax.swing.JTextField tfcliente;
    private javax.swing.JTextField tfcodp;
    private javax.swing.JTextField tfdescobs;
    private javax.swing.JTextField tfdescobspesq;
    private javax.swing.JTextField tfdoc;
    private com.toedter.calendar.JDateChooser tfdte;
    private com.toedter.calendar.JDateChooser tfdtef;
    private com.toedter.calendar.JDateChooser tfdtei;
    private com.toedter.calendar.JDateChooser tfdtvf;
    private com.toedter.calendar.JDateChooser tfdtvi;
    private javax.swing.JTextField tfidt;
    private javax.swing.JSpinner tfqtdp;
    private javax.swing.JTextField tftotal;
    private javax.swing.JTextField tftotts;
    private javax.swing.JSpinner tfvenc;
    private javax.swing.JTextField tfvlrparcela;
    private com.toedter.calendar.JDateChooser txtdatabaixa;
    // End of variables declaration//GEN-END:variables

    private void formtitulo() {

        tbts.getColumnModel().getColumn(0).setPreferredWidth(43);
        tbts.getColumnModel().getColumn(1).setPreferredWidth(65);
        tbts.getColumnModel().getColumn(2).setPreferredWidth(60);
        tbts.getColumnModel().getColumn(3).setPreferredWidth(65);
        tbts.getColumnModel().getColumn(4).setPreferredWidth(138);
        tbts.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbts.getColumnModel().getColumn(6).setPreferredWidth(47);
        tbts.getColumnModel().getColumn(7).setPreferredWidth(90);
        tbts.getColumnModel().getColumn(8).setPreferredWidth(80);
        tbts.getColumnModel().getColumn(9).setPreferredWidth(57);
        tbts.getColumnModel().getColumn(10).setPreferredWidth(80);
        tbts.getColumnModel().getColumn(11).setPreferredWidth(90);
        tbts.getColumnModel().getColumn(12).setPreferredWidth(90);
        tbts.getColumnModel().getColumn(13).setPreferredWidth(90);

    }

    public void populatitulo() {

        DefaultTableModel t = (DefaultTableModel) tbts.getModel();
        t.setNumRows(0);

        int baixado;
        if (cbbaixado.isSelected()) {
            baixado = 1;
        } else {
            baixado = 0;
        }

        int tamanho;
        List<Titulo> lista = tcontrol.listatspesq(
                cbtipo.getSelectedItem().toString(),
                Integer.parseInt(tfcodp.getText()),
                baixado,
                Util.datatoStringUS(tfdtei.getDate()),
                Util.datatoStringUS(tfdtef.getDate()),
                Util.datatoStringUS(tfdtvi.getDate()),
                Util.datatoStringUS(tfdtvf.getDate()),
                tfdescobspesq.getText(),
                "",
                "");

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum título encontrado com o filtro selecionado");
            dataspesq();
            tfdescobspesq.setText("");
            tfcodp.setText("0");
            tfcliente.setText("");
            btnnovo.setEnabled(true);
        }

        tamanho = lista.size();
        for (int i = 0; i < tamanho; i++) {
            Titulo titulo = lista.get(i);

            t.addRow(new Object[]{0});

            t.setValueAt(titulo.getId(), i, 0);
            t.setValueAt(titulo.getDoc(), i, 1);
            t.setValueAt(titulo.getTipo(), i, 2);
            t.setValueAt(titulo.getIdclifor(), i, 3);
            t.setValueAt(titulo.getClifor(), i, 4);
            t.setValueAt(titulo.getDescos(), i, 5);
            t.setValueAt(titulo.getQtdparcela(), i, 6);
            t.setValueAt(titulo.getVlrparcela(), i, 7);
            t.setValueAt(titulo.getFormpag(), i, 8);
            t.setValueAt(titulo.getVlrtotal(), i, 9);
            t.setValueAt(Util.convertedataBR(titulo.getDtv()), i, 10);
            if (titulo.getDtb() == null) {
                titulo.setDtb("");
                t.setValueAt(Util.convertedataBR(titulo.getDtb()), i, 11);
            } else {
                t.setValueAt(Util.convertedataBR(titulo.getDtb()), i, 11);
            }

            t.setValueAt(Util.convertedataBR(titulo.getDte()), i, 12);
            t.setValueAt(titulo.getVlrbaixa(), i, 13);

            if (titulo.isBaixado()) {
                t.setValueAt("Baixado", i, 14);

            } else {

                t.setValueAt("Não", i, 14);
            }

        }
    }

    private void calcula() {
        if (!tftotal.getText().isEmpty() && !tfqtdp.getValue().toString().isEmpty()) {
            Double vtot = Double.parseDouble(tftotal.getText().replace(",", "."));
            int parc = Integer.parseInt(tfqtdp.getValue().toString().replace(",", "."));
            Double vparcela = vtot / parc;
            tfvlrparcela.setText(dc.format(vparcela));

        }

    }

    public void dataspesq() {

        tfdtei.setDate(Util.dataBR("01/01/1950"));
        tfdtvi.setDate(Util.dataBR("01/01/1950"));
        tfdtef.setDate(Util.dataBR("30/12/2050"));
        tfdtvf.setDate(Util.dataBR("30/12/2050"));

    }

}
